//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t entry_point(int32_t i_a1, int32_t i_a2);
int32_t function_10584(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_105a4(void);
int32_t function_105b0(void);
int32_t function_105bc(void);
int32_t function_105c8(void);
int32_t function_105d4(void);
int32_t function_105e0(void);
int32_t function_105ec(void);
int32_t function_105f8(void);
int32_t function_10604(void);
int32_t function_10610(void);
int32_t function_1061c(void);
int32_t function_10628(void);
int32_t function_10634(void);
int32_t function_10640(void);
int32_t function_1064c(void);
int32_t function_10658(void);
int32_t function_10664(void);
int32_t function_10670(void);
int32_t function_1067c(void);
int32_t function_10688(void);
int32_t function_10694(void);
int32_t function_106a0(int32_t i_a1, int32_t i_a2);
int32_t function_108b0(void);
int32_t function_108d4(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4);
int32_t function_108fe(int32_t i_a1, int32_t i_a2);
int32_t function_10924(void);
int32_t function_1093c(void);
int32_t function_10940(int32_t i_a1);
int32_t function_109a8(void);
int32_t function_109c0(void);
int32_t function_10af8(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10b34(void);
int32_t function_10b38(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);

// --------------------- Global Variables ---------------------

int32_t i_g1 = 0x1093d; // 0x20f10
int32_t i_g2 = 0;       // 0x21060
char *p_g3;             // 0x2106c

// ------------------------ Functions -------------------------

// Address range: 0x10584 - 0x10590
int32_t function_10584(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10584
    return function_108b0();
}

// Address range: 0x105a4 - 0x105b0
int32_t function_105a4(void) {
    // 0x105a4
    int32_t i_v1; // 0x105a4
    return i_v1;
}

// Address range: 0x105b0 - 0x105bc
int32_t function_105b0(void) {
    // 0x105b0
    int32_t i_v1; // 0x105b0
    return i_v1;
}

// Address range: 0x105bc - 0x105c8
int32_t function_105bc(void) {
    // 0x105bc
    int32_t i_v1; // 0x105bc
    return i_v1;
}

// Address range: 0x105c8 - 0x105d4
int32_t function_105c8(void) {
    // 0x105c8
    int32_t i_v1; // 0x105c8
    return i_v1;
}

// Address range: 0x105d4 - 0x105e0
int32_t function_105d4(void) {
    // 0x105d4
    int32_t i_v1; // 0x105d4
    return i_v1;
}

// Address range: 0x105e0 - 0x105ec
int32_t function_105e0(void) {
    // 0x105e0
    int32_t i_v1; // 0x105e0
    return i_v1;
}

// Address range: 0x105ec - 0x105f8
int32_t function_105ec(void) {
    // 0x105ec
    int32_t i_v1; // 0x105ec
    return i_v1;
}

// Address range: 0x105f8 - 0x10604
int32_t function_105f8(void) {
    // 0x105f8
    int32_t i_v1; // 0x105f8
    return i_v1;
}

// Address range: 0x10604 - 0x10610
int32_t function_10604(void) {
    // 0x10604
    int32_t i_v1; // 0x10604
    return i_v1;
}

// Address range: 0x10610 - 0x1061c
int32_t function_10610(void) {
    // 0x10610
    int32_t i_v1; // 0x10610
    return i_v1;
}

// Address range: 0x1061c - 0x10628
int32_t function_1061c(void) {
    // 0x1061c
    int32_t i_v1; // 0x1061c
    return i_v1;
}

// Address range: 0x10628 - 0x10634
int32_t function_10628(void) {
    // 0x10628
    int32_t i_v1; // 0x10628
    return i_v1;
}

// Address range: 0x10634 - 0x10640
int32_t function_10634(void) {
    // 0x10634
    int32_t i_v1; // 0x10634
    return i_v1;
}

// Address range: 0x10640 - 0x1064c
int32_t function_10640(void) {
    // 0x10640
    int32_t i_v1; // 0x10640
    return i_v1;
}

// Address range: 0x1064c - 0x10658
int32_t function_1064c(void) {
    // 0x1064c
    int32_t i_v1; // 0x1064c
    return i_v1;
}

// Address range: 0x10658 - 0x10664
int32_t function_10658(void) {
    // 0x10658
    int32_t i_v1; // 0x10658
    return i_v1;
}

// Address range: 0x10664 - 0x10670
int32_t function_10664(void) {
    // 0x10664
    int32_t i_v1; // 0x10664
    return i_v1;
}

// Address range: 0x10670 - 0x1067c
int32_t function_10670(void) {
    // 0x10670
    int32_t i_v1; // 0x10670
    return i_v1;
}

// Address range: 0x1067c - 0x10688
int32_t function_1067c(void) {
    // 0x1067c
    int32_t i_v1; // 0x1067c
    return i_v1;
}

// Address range: 0x10688 - 0x10694
int32_t function_10688(void) {
    // 0x10688
    int32_t i_v1; // 0x10688
    return i_v1;
}

// Address range: 0x10694 - 0x106a0
int32_t function_10694(void) {
    // 0x10694
    int32_t i_v1; // 0x10694
    return i_v1;
}

// Address range: 0x106a0 - 0x10880
int32_t function_106a0(int32_t i_a1, int32_t i_a2) {
    // 0x106a0
    function_105a4();
    while (true) {
        // 0x106ec
        if (function_109c0() == 0) {
            while (true) {
                // 0x106fc
                function_105f8();
                function_10940(1);
                function_10604();
                if (function_109c0() != 1) {
                    while (true) {
                    lab_generated_0:
                        function_105f8();
                        // 0x10838
                        function_105ec();
                        goto lab_0x10714;
                    }
                }
            lab_0x10814_2:
                // 0x10814
                function_10940(0);
                if (function_109c0() != 0) {
                    // break -> 0x1082c
                    break;
                }
            }
        }
        // 0x1082c
        function_105c8();
    }
lab_0x10854:
    // 0x10854
    function_10940(0);
    if (i_a1 < 2) {
        // 0x10874
        function_105c8();
        // 0x1086c
        function_10634();
        // 0x10874
        function_105c8();
        goto lab_0x1086c;
    } else {
        // 0x10860
        function_105bc();
        // 0x1086c
        function_10634();
        // 0x10874
        function_105c8();
        goto lab_0x1086c;
    }
lab_0x10714:
    // 0x10714
    if (function_109c0() == 1) {
        // break -> 0x10814
        goto lab_0x10814_2;
    }
    goto lab_generated_1;
}

// Address range: 0x10880 - 0x108a8
int32_t entry_point(int32_t i_a1, int32_t i_a2) {
    // 0x10880
    function_10610();
    return function_10694();
}

// Address range: 0x108b0 - 0x108cc
int32_t function_108b0(void) {
    // 0x108b0
    if (i_g2 == 0) {
        int32_t i_v1; // 0x108b0
        return i_v1;
    }
    // 0x108c8
    return function_10628();
}

// Address range: 0x108d4 - 0x108fc
int32_t function_108d4(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4) {
    // 0x108d4
    bool i_v1; // 0x108d4
    if (!i_v1 && false) {
        __asm_svclt(0x4770);
    }
    return i_a1;
}

// Address range: 0x108fe - 0x10922
int32_t function_108fe(int32_t i_a1, int32_t i_a2) {
    // 0x108fe
    return i_a1 | 0x20000;
}

// Address range: 0x10924 - 0x1093c
int32_t function_10924(void) {
    // 0x10924
    int32_t i_v1; // 0x10924
    if (*(char *)&p_g3 == 0) {
        // 0x10932
        int32_t i_v2;                                       // 0x10924
        int32_t i_v3 = function_108d4(i_v2, i_v2, i_v2, 0); // 0x10932
        *(char *)&p_g3 = 1;
        i_v1 = i_v3;
    }
    // 0x1093a
    return i_v1;
}

// Address range: 0x1093c - 0x1093e
int32_t function_1093c(void) {
    // 0x1093c
    int32_t i_v1; // 0x1093c
    return i_v1;
}

// Address range: 0x10940 - 0x109a8
int32_t function_10940(int32_t i_a1) {
    // 0x10940
    function_1064c();
    function_1067c();
    function_1061c();
    function_1067c();
    return function_1061c();
}

// Address range: 0x109a8 - 0x109c0
int32_t function_109a8(void) {
    // 0x109a8
    function_10658();
    return 0;
}

// Address range: 0x109c0 - 0x10af8
int32_t function_109c0(void) {
    // 0x109c0
    function_1064c();
    function_1067c();
    if (function_10658() == 0) {
        // 0x10a74
        function_1067c();
        int32_t i_v1; // 0x109c0
        if (function_10688() == 0) {
            // 0x10ae4
            function_10604();
            i_v1 = -1;
        } else {
            // 0x10aa0
            function_105b0();
            function_10664();
            int32_t i_v2; // 0x109c0
            i_v1 = i_v2 != 0;
        }
        // 0x10ac4
        return i_v1;
    }
    // 0x10a00
    if (function_10688() == 0) {
        // 0x10acc
        function_10604();
        return -1;
    }
    // 0x10a1c
    function_1067c();
    function_10640();
    if (function_105e0() != 1) {
        // 0x10a54
        function_10604();
    }
    // 0x10a60
    function_10664();
    return -1;
}

// Address range: 0x10af8 - 0x10b2c
int32_t function_10af8(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_10584(i_a1, i_a2, i_a3, i_a4); // 0x10b08
    int32_t i_v2 =
        (int32_t) "system" + 0x10b08 - (int32_t)&i_g1 >> 2 == 0 ? i_v1 : i_a1;
    return i_v2;
}

// Address range: 0x10b34 - 0x10b36
int32_t function_10b34(void) {
    // 0x10b34
    int32_t i_v1; // 0x10b34
    return i_v1;
}

// Address range: 0x10b38 - 0x10b40
int32_t function_10b38(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10b38
    return i_a1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.3)
// Detected functions: 35
