//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t __libc_start_main(void);
int32_t abort(void);
int32_t access(void);
int32_t daemon(void);
int32_t entry_point(int32_t i_a1, int32_t i_a2);
int32_t exit(void);
int32_t fclose(void);
int32_t fopen(void);
int32_t fprintf(void);
int32_t function_8484(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_84f8(void);
int32_t function_854c(int32_t i_a1, int32_t i_a2);
int32_t function_869c(void);
int32_t function_86c0(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4);
int32_t function_86f8(int32_t *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_8738(void);
int32_t function_8760(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_8794(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_87ac(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_87c4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_880c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_8870(void);
int32_t function_8874(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t signal(void);
int32_t sleep(void);
int32_t sscanf(void);
int32_t time(void);
int32_t unlink(void);

// --------------------- Global Variables ---------------------

int32_t i_g1 = 0x8760;      // 0x108b0
int32_t i_g2 = 0x8738;      // 0x108b4
int32_t i_g3 = 0;           // 0x108b8
char *p_g4;                 // 0x109f4
int32_t i_g5 = 0x8540;      // 0x82f8
int32_t i_g6 = -0x1cae0000; // 0x86ac

// ------------------------ Functions -------------------------

// Address range: 0x8484 - 0x8490
int32_t function_8484(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x8484
    return function_869c();
}

// Address range: 0x84a4 - 0x84b0
int32_t fopen(void) {
    // 0x84a4
    int32_t i_v1; // 0x84a4
    return i_v1;
}

// Address range: 0x84b0 - 0x84bc
int32_t signal(void) {
    // 0x84b0
    int32_t i_v1; // 0x84b0
    return i_v1;
}

// Address range: 0x84bc - 0x84c8
int32_t time(void) {
    // 0x84bc
    int32_t i_v1; // 0x84bc
    return i_v1;
}

// Address range: 0x84c8 - 0x84d4
int32_t sleep(void) {
    // 0x84c8
    int32_t i_v1; // 0x84c8
    return i_v1;
}

// Address range: 0x84d4 - 0x84e0
int32_t unlink(void) {
    // 0x84d4
    int32_t i_v1; // 0x84d4
    return i_v1;
}

// Address range: 0x84e0 - 0x84ec
int32_t daemon(void) {
    // 0x84e0
    int32_t i_v1; // 0x84e0
    return i_v1;
}

// Address range: 0x84ec - 0x84f8
int32_t __libc_start_main(void) {
    // 0x84ec
    int32_t i_v1; // 0x84ec
    return i_v1;
}

// Address range: 0x84f8 - 0x8504
int32_t function_84f8(void) {
    // 0x84f8
    int32_t i_v1; // 0x84f8
    return i_v1;
}

// Address range: 0x8504 - 0x8510
int32_t exit(void) {
    // 0x8504
    int32_t i_v1; // 0x8504
    return i_v1;
}

// Address range: 0x8510 - 0x851c
int32_t fprintf(void) {
    // 0x8510
    int32_t i_v1; // 0x8510
    return i_v1;
}

// Address range: 0x851c - 0x8528
int32_t sscanf(void) {
    // 0x851c
    int32_t i_v1; // 0x851c
    return i_v1;
}

// Address range: 0x8528 - 0x8534
int32_t access(void) {
    // 0x8528
    int32_t i_v1; // 0x8528
    return i_v1;
}

// Address range: 0x8534 - 0x8540
int32_t fclose(void) {
    // 0x8534
    int32_t i_v1; // 0x8534
    return i_v1;
}

// Address range: 0x8540 - 0x854c
int32_t abort(void) {
    // 0x8540
    int32_t i_v1; // 0x8540
    return i_v1;
}

// Address range: 0x854c - 0x8654
int32_t function_854c(int32_t i_a1, int32_t i_a2) {
    // 0x854c
    int32_t i_v1; // 0x854c
    int32_t i_v2 = i_v1;
    int32_t i_v3 = -1; // bp-20, 0x8568
    if (access() == 0) {
        // 0x864c
        return exit();
    }
    int32_t i_v4 = i_a1 < 2 ? 600 : -1; // 0x8580
    int32_t i_v5;                       // 0x854c
    if (i_a1 > 1) {
        // 0x8584
        sscanf();
        int32_t i_v6 = i_v3; // 0x8594
        int32_t i_v7 = i_v6 > 2 ? i_v6 : 2;
        i_v4 = i_v6 > 1 == i_v7 > 1799 ? 1800 : i_v7;
        i_v5 = &i_v3;
    }
    // 0x85a4
    signal();
    signal();
    signal();
    signal();
    time();
    function_87c4(i_v4, 0x8794, i_v5, i_v2);
    int32_t i_v8 = daemon(); // 0x8600
    if (i_v4 + i_v2 < i_v2) {
        // 0x8628
        unlink();
        return 0;
    }
    while (true) {
        // 0x8604
        function_87ac(i_v8, 0, i_v5, i_v2);
        time();
        i_v8 = function_87c4(i_v4, 0, i_v5, i_v2);
    }
}

// Address range: 0x8660 - 0x8690
int32_t entry_point(int32_t i_a1, int32_t i_a2) {
    // 0x8660
    __libc_start_main();
    return abort();
}

// Address range: 0x869c - 0x86b8
int32_t function_869c(void) {
    int32_t i_v1 = *(int32_t *)((int32_t)&i_g6 + (int32_t)&i_g5 + 68); // 0x86a8
    if (i_v1 == 0) {
        int32_t i_v2; // 0x869c
        return i_v2;
    }
    // 0x86b4
    return function_84f8();
}

// Address range: 0x86c0 - 0x86ec
int32_t function_86c0(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4) {
    // 0x86c0
    return (int32_t)&p_g4;
}

// Address range: 0x86f8 - 0x872c
int32_t function_86f8(int32_t *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x86f8
    return (int32_t)&p_g4;
}

// Address range: 0x8738 - 0x875c
int32_t function_8738(void) {
    // 0x8738
    int32_t i_v1; // 0x8738
    if (*(char *)&p_g4 != 0) {
        return i_v1;
    }
    int32_t i_v2 = function_86c0(i_v1, i_v1, i_v1, 0); // 0x874c
    *(char *)&p_g4 = 1;
    return i_v2;
}

// Address range: 0x8760 - 0x878c
int32_t function_8760(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x8760
    return function_86f8(&i_g3, i_a2, i_a3, i_a4);
}

// Address range: 0x8794 - 0x87ac
int32_t function_8794(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x8794
    unlink();
    return exit();
}

// Address range: 0x87ac - 0x87c4
int32_t function_87ac(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x87ac
    sleep();
    return sleep();
}

// Address range: 0x87c4 - 0x8800
int32_t function_87c4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x87c4
    if (fopen() == 0) {
        // 0x87f8
        return exit();
    }
    // 0x87e0
    fprintf();
    return fclose();
}

// Address range: 0x880c - 0x8868
int32_t function_880c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_8484(i_a1, i_a2, i_a3, i_a4); // 0x8828
    int32_t i_v2 = (int32_t)&i_g2 - (int32_t)&i_g1 >> 2 == 0 ? i_v1 : i_a1;
    return i_v2;
}

// Address range: 0x8870 - 0x8874
int32_t function_8870(void) {
    // 0x8870
    int32_t i_v1; // 0x8870
    return i_v1;
}

// Address range: 0x8874 - 0x887c
int32_t function_8874(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x8874
    return i_a1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.8.x)
// Detected functions: 28
