//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t __libc_start_main(void);
int32_t abort(void);
int32_t access(void);
int32_t entry_point(int32_t i_a1, int32_t i_a2);
int32_t execvp(void);
int32_t exit(void);
int32_t fclose(void);
int32_t fopen(void);
int32_t fork(void);
int32_t fscanf(void);
int32_t function_8530(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_85e0(void);
int32_t function_8628(int32_t i_a1, int32_t i_a2);
int32_t function_8824(void);
int32_t function_8848(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4);
int32_t function_8880(int32_t *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_88c0(void);
int32_t function_88e8(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_891c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_893c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_895c(char *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_8974(void);
int32_t function_8a58(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_8abc(void);
int32_t function_8ac0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t fwrite(void);
int32_t gettimeofday(void);
int32_t printf(void);
int32_t puts(void);
int32_t sleep(void);
int32_t system(void);
int32_t usleep(void);
int32_t wait(void);

// --------------------- Global Variables ---------------------

int32_t i_g1 = 0;           // 0x10d18
int32_t i_g2 = 0;           // 0x10e58
char *p_g3;                 // 0x10e64
int32_t i_g4 = 18;          // 0x8290
int32_t i_g5 = 0;           // 0x829c
int32_t i_g6 = -0x1e4f9eba; // 0x8a80

// ------------------------ Functions -------------------------

// Address range: 0x8530 - 0x853c
int32_t function_8530(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x8530
    return function_8824();
}

// Address range: 0x8550 - 0x855c
int32_t printf(void) {
    // 0x8550
    int32_t i_v1; // 0x8550
    return i_v1;
}

// Address range: 0x855c - 0x8568
int32_t fscanf(void) {
    // 0x855c
    int32_t i_v1; // 0x855c
    return i_v1;
}

// Address range: 0x8568 - 0x8574
int32_t fopen(void) {
    // 0x8568
    int32_t i_v1; // 0x8568
    return i_v1;
}

// Address range: 0x8574 - 0x8580
int32_t execvp(void) {
    // 0x8574
    int32_t i_v1; // 0x8574
    return i_v1;
}

// Address range: 0x8580 - 0x858c
int32_t sleep(void) {
    // 0x8580
    int32_t i_v1; // 0x8580
    return i_v1;
}

// Address range: 0x858c - 0x8598
int32_t wait(void) {
    // 0x858c
    int32_t i_v1; // 0x858c
    return i_v1;
}

// Address range: 0x8598 - 0x85a4
int32_t fwrite(void) {
    // 0x8598
    int32_t i_v1; // 0x8598
    return i_v1;
}

// Address range: 0x85a4 - 0x85b0
int32_t usleep(void) {
    // 0x85a4
    int32_t i_v1; // 0x85a4
    return i_v1;
}

// Address range: 0x85b0 - 0x85bc
int32_t gettimeofday(void) {
    // 0x85b0
    int32_t i_v1; // 0x85b0
    return i_v1;
}

// Address range: 0x85bc - 0x85c8
int32_t puts(void) {
    // 0x85bc
    int32_t i_v1; // 0x85bc
    return i_v1;
}

// Address range: 0x85c8 - 0x85d4
int32_t __libc_start_main(void) {
    // 0x85c8
    int32_t i_v1; // 0x85c8
    return i_v1;
}

// Address range: 0x85d4 - 0x85e0
int32_t system(void) {
    // 0x85d4
    int32_t i_v1; // 0x85d4
    return i_v1;
}

// Address range: 0x85e0 - 0x85ec
int32_t function_85e0(void) {
    // 0x85e0
    int32_t i_v1; // 0x85e0
    return i_v1;
}

// Address range: 0x85ec - 0x85f8
int32_t exit(void) {
    // 0x85ec
    int32_t i_v1; // 0x85ec
    return i_v1;
}

// Address range: 0x85f8 - 0x8604
int32_t access(void) {
    // 0x85f8
    int32_t i_v1; // 0x85f8
    return i_v1;
}

// Address range: 0x8604 - 0x8610
int32_t fclose(void) {
    // 0x8604
    int32_t i_v1; // 0x8604
    return i_v1;
}

// Address range: 0x8610 - 0x861c
int32_t fork(void) {
    // 0x8610
    int32_t i_v1; // 0x8610
    return i_v1;
}

// Address range: 0x861c - 0x8628
int32_t abort(void) {
    // 0x861c
    int32_t i_v1; // 0x861c
    return i_v1;
}

// Address range: 0x8628 - 0x87c4
int32_t function_8628(int32_t i_a1, int32_t i_a2) {
    // 0x8628
    printf();
    int32_t i_v1 = 0;
    int32_t i_v2 = (int32_t) "14:30:27"; // 0x8644
    int32_t i_v3;                        // 0x8628
    int32_t i_v4;                        // 0x8628
    int32_t i_v5;                        // 0x8628
    while (true) {
        int32_t i_v6 = i_v2; // 0x8654
        int32_t i_v7;        // 0x8628
        int32_t i_v8 = i_v7; // 0x8654
        int32_t i_v9 = i_v7; // 0x8654
        if (function_8974() == 0) {
            while (true) {
                // 0x8658
                function_891c(gettimeofday(), 0, i_v6, i_v8);
                puts();
                i_v3 = i_v6;
                i_v4 = i_v8;
                if (function_8974() != 1) {
                    while (true) {
                    lab_generated_0:
                        gettimeofday();
                        while (i_v1 >= 0x2dc6c1) {
                            // 0x86bc
                            puts();
                            if (function_8974() == 0) {
                                function_891c(0, i_v5, i_v1, 0x2dc6c0);
                                function_893c(sleep(), i_v5, i_v1, 0x2dc6c0);
                                sleep();
                                while (function_8974() == 0) {
                                    // 0x86c8
                                    function_891c(0, i_v5, i_v1, 0x2dc6c0);
                                    function_893c(sleep(), i_v5, i_v1,
                                                  0x2dc6c0);
                                    sleep();
                                }
                            }
                            // 0x86f0
                            puts();
                            int32_t i_v10 = fork(); // 0x86f8
                            if (i_v10 < 0) {
                                // 0x878c
                                puts();
                                goto lab_0x8674;
                            }
                            if (i_v10 == 0) {
                                // break (via goto) -> 0x8798
                                goto lab_0x8798;
                            }
                            // 0x8708
                            wait();
                            int32_t i_v11 = puts(); // 0x8718
                            int32_t i_v12 = 100;
                            function_891c(i_v11, i_v5, i_v1, 0x2dc6c0);
                            function_893c(usleep(), i_v5, i_v1, 0x2dc6c0);
                            i_v11 = usleep();
                            int32_t i_v13 = i_v12 - 1; // 0x8740
                            while (i_v12 != 1) {
                                // 0x871c
                                i_v12 = i_v13;
                                function_891c(i_v11, i_v5, i_v1, 0x2dc6c0);
                                function_893c(usleep(), i_v5, i_v1, 0x2dc6c0);
                                i_v11 = usleep();
                                i_v13 = i_v12 - 1;
                            }
                            // 0x8744
                            puts();
                            i_v3 = i_v1;
                            i_v4 = 0x2dc6c0;
                            if (function_8974() == 1) {
                                // break (via goto) -> 0x875c
                                goto lab_0x875c_2;
                            }
                            gettimeofday();
                        }
                        // 0x877c
                        usleep();
                        goto lab_0x8674;
                    }
                }
            lab_0x875c_2:
                // 0x875c
                function_893c(1, 0, i_v3, i_v4);
                i_v6 = i_v3;
                i_v8 = i_v4;
                i_v2 = i_v3;
                i_v9 = i_v4;
                if (function_8974() != 0) {
                    // break -> 0x8770
                    break;
                }
            }
        }
        // 0x8770
        sleep();
        i_v7 = i_v9;
    }
lab_0x8798:
    // 0x8798
    function_893c(0, i_v5, i_v1, 0x2dc6c0);
    if (i_a1 < 2) {
        // 0x87b8
        sleep();
        // 0x87b0
        exit();
        // 0x87b8
        sleep();
        // 0x87b0
        exit();
        // 0x87b8
        sleep();
        goto lab_0x87b0;
    } else {
        // 0x87a4
        execvp();
        // 0x87b0
        exit();
        // 0x87b8
        sleep();
        goto lab_0x87b0;
    }
lab_0x8674:
    // 0x8674
    i_v3 = i_v1;
    i_v4 = 0x2dc6c0;
    if (function_8974() == 1) {
        // break -> 0x875c
        goto lab_0x875c_2;
    }
    goto lab_generated_1;
}

// Address range: 0x87e8 - 0x8818
int32_t entry_point(int32_t i_a1, int32_t i_a2) {
    // 0x87e8
    __libc_start_main();
    return abort();
}

// Address range: 0x8824 - 0x8840
int32_t function_8824(void) {
    // 0x8824
    if (i_g2 == 0) {
        int32_t i_v1; // 0x8824
        return i_v1;
    }
    // 0x883c
    return function_85e0();
}

// Address range: 0x8848 - 0x8874
int32_t function_8848(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4) {
    // 0x8848
    return (int32_t)&p_g3;
}

// Address range: 0x8880 - 0x88b4
int32_t function_8880(int32_t *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x8880
    return (int32_t)&p_g3;
}

// Address range: 0x88c0 - 0x88e4
int32_t function_88c0(void) {
    // 0x88c0
    int32_t i_v1; // 0x88c0
    if (*(char *)&p_g3 != 0) {
        return i_v1;
    }
    int32_t i_v2 = function_8848(i_v1, i_v1, i_v1, 0); // 0x88d4
    *(char *)&p_g3 = 1;
    return i_v2;
}

// Address range: 0x88e8 - 0x8914
int32_t function_88e8(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x88e8
    return function_8880(&i_g1, i_a2, i_a3, i_a4);
}

// Address range: 0x891c - 0x893c
int32_t function_891c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x891c
    system();
    return system();
}

// Address range: 0x893c - 0x895c
int32_t function_893c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x893c
    system();
    return system();
}

// Address range: 0x895c - 0x8974
int32_t function_895c(char *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    uint32_t i_v1 = access(); // 0x8964
    return (i_v1 > 1 ? i_v1 : 1) - i_v1;
}

// Address range: 0x8974 - 0x8a30
int32_t function_8974(void) {
    // 0x8974
    int32_t i_v1; // 0x8974
    int32_t i_v2 =
        function_895c("/sys/class/gpio/gpio921", i_v1, i_v1, i_v1); // 0x8980
    int32_t i_v3 = fopen();
    if (i_v2 != 0) {
        int32_t i_v4; // 0x8974
        if (i_v3 == 0) {
            // 0x8a10
            puts();
            i_v4 = -1;
        } else {
            // 0x89ec
            fscanf();
            fclose();
            i_v4 = i_v1 != 0;
        }
        // 0x89d0
        return i_v4;
    }
    if (i_v3 == 0) {
        // 0x8a20
        puts();
        // 0x89d0
        return -1;
    }
    // 0x89a0
    if (fwrite() != 1) {
        // 0x89bc
        puts();
    }
    // 0x89c4
    fclose();
    // 0x89d0
    return -1;
}

// Address range: 0x8a58 - 0x8ab4
int32_t function_8a58(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_8530(i_a1, i_a2, i_a3, i_a4); // 0x8a74
    int32_t i_v2 =
        (int32_t)&i_g5 + 0x8a78 - ((int32_t)&i_g6 + (int32_t)&i_g4) >> 2 == 0
            ? i_v1
            : i_a1;
    return i_v2;
}

// Address range: 0x8abc - 0x8ac0
int32_t function_8abc(void) {
    // 0x8abc
    int32_t i_v1; // 0x8abc
    return i_v1;
}

// Address range: 0x8ac0 - 0x8ac8
int32_t function_8ac0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x8ac0
    return i_a1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.8.x)
// Detected functions: 33
