//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t __ctype_tolower_loc(void);
int32_t __errno_location(void);
int32_t __libc_start_main(void);
int32_t abort(void);
int32_t close(void);
int32_t entry_point(int32_t i_a1, int32_t i_a2);
int32_t exit(void);
int32_t fflush(void);
int32_t fprintf(void);
int32_t function_8530(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_8598(void);
int32_t function_861c(int32_t i_a1, int32_t i_a2);
int32_t function_8954(void);
int32_t function_8978(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4);
int32_t function_89b0(int32_t *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_89f0(void);
int32_t function_8a18(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_8a4c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_8ab0(void);
int32_t function_8ab4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t mmap(void);
int32_t munmap(void);
int32_t open(void);
int32_t printf(void);
int32_t puts(void);
int32_t sprintf(void);
int32_t strerror(void);
int32_t strtoul(void);

// --------------------- Global Variables ---------------------

int32_t i_g1 = 0;           // 0x10c80
int32_t i_g2 = 0;           // 0x10dc8
char *p_g3;                 // 0x10dd0
int32_t i_g4 = 19;          // 0x8204
int32_t i_g5 = -0x5a4af0f5; // 0x8210
int32_t i_g6 = -0x1cae0000; // 0x8964
int32_t i_g7 = -0x1e4f9eba; // 0x8a74

// ------------------------ Functions -------------------------

// Address range: 0x8530 - 0x853c
int32_t function_8530(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x8530
    return function_8954();
}

// Address range: 0x8550 - 0x855c
int32_t printf(void) {
    // 0x8550
    int32_t i_v1; // 0x8550
    return i_v1;
}

// Address range: 0x855c - 0x8568
int32_t fflush(void) {
    // 0x855c
    int32_t i_v1; // 0x855c
    return i_v1;
}

// Address range: 0x8568 - 0x8574
int32_t puts(void) {
    // 0x8568
    int32_t i_v1; // 0x8568
    return i_v1;
}

// Address range: 0x8574 - 0x8580
int32_t __libc_start_main(void) {
    // 0x8574
    int32_t i_v1; // 0x8574
    return i_v1;
}

// Address range: 0x8580 - 0x858c
int32_t strerror(void) {
    // 0x8580
    int32_t i_v1; // 0x8580
    return i_v1;
}

// Address range: 0x858c - 0x8598
int32_t __ctype_tolower_loc(void) {
    // 0x858c
    int32_t i_v1; // 0x858c
    return i_v1;
}

// Address range: 0x8598 - 0x85a4
int32_t function_8598(void) {
    // 0x8598
    int32_t i_v1; // 0x8598
    return i_v1;
}

// Address range: 0x85a4 - 0x85b0
int32_t open(void) {
    // 0x85a4
    int32_t i_v1; // 0x85a4
    return i_v1;
}

// Address range: 0x85b0 - 0x85bc
int32_t exit(void) {
    // 0x85b0
    int32_t i_v1; // 0x85b0
    return i_v1;
}

// Address range: 0x85bc - 0x85c8
int32_t strtoul(void) {
    // 0x85bc
    int32_t i_v1; // 0x85bc
    return i_v1;
}

// Address range: 0x85c8 - 0x85d4
int32_t mmap(void) {
    // 0x85c8
    int32_t i_v1; // 0x85c8
    return i_v1;
}

// Address range: 0x85d4 - 0x85e0
int32_t fprintf(void) {
    // 0x85d4
    int32_t i_v1; // 0x85d4
    return i_v1;
}

// Address range: 0x85e0 - 0x85ec
int32_t __errno_location(void) {
    // 0x85e0
    int32_t i_v1; // 0x85e0
    return i_v1;
}

// Address range: 0x85ec - 0x85f8
int32_t munmap(void) {
    // 0x85ec
    int32_t i_v1; // 0x85ec
    return i_v1;
}

// Address range: 0x85f8 - 0x8604
int32_t sprintf(void) {
    // 0x85f8
    int32_t i_v1; // 0x85f8
    return i_v1;
}

// Address range: 0x8604 - 0x8610
int32_t abort(void) {
    // 0x8604
    int32_t i_v1; // 0x8604
    return i_v1;
}

// Address range: 0x8610 - 0x861c
int32_t close(void) {
    // 0x8610
    int32_t i_v1; // 0x8610
    return i_v1;
}

// Address range: 0x861c - 0x88ec
int32_t function_861c(int32_t i_a1, int32_t i_a2) {
    if (i_a1 < 2) {
        // 0x8880
        fprintf();
        exit();
        // 0x889c
        __errno_location();
        strerror();
        goto lab_0x8868;
    } else {
        int32_t i_v1 = strtoul(); // 0x8640
        int32_t i_v2 = 119;       // 0x8650
        if (i_a1 != 2) {
            int32_t i_v3 = __ctype_tolower_loc();                 // 0x8784
            unsigned char i_v4 = *(char *)*(int32_t *)(i_a2 + 8); // 0x878c
            i_v2 = *(int32_t *)(4 * (int32_t)i_v4 + *(int32_t *)i_v3);
        }
        // 0x8654
        if (open() == -1) {
            // 0x8844
            __errno_location();
            strerror();
            goto lab_0x8868;
        } else {
            // 0x8670
            puts();
            fflush();
            int32_t i_v5 = mmap(); // 0x86a4
            if (i_v5 == -1) {
                // 0x889c
                __errno_location();
                strerror();
                goto lab_0x8868;
            } else {
                // 0x86b4
                printf();
                fflush();
                int32_t i_v6 = __asm_ubfx(i_v1, 0, 12) + i_v5; // 0x86d0
                int32_t i_v7 = i_v6;                           // 0x861c
                switch (i_v2) {
                case 119: {
                    // 0x879c
                    i_v7 = i_v6 & -4;
                }
                case 98: {
                lab_0x8720:
                    // 0x8720
                    sprintf();
                    printf();
                    fflush();
                    if (i_a1 > 3) {
                        int32_t i_v8 = strtoul(); // 0x87bc
                        switch (i_v2) {
                        case 104: {
                            // 0x8820
                            *(int16_t *)(i_v7 & -2) = (int16_t)i_v8;
                            // break -> 0x87e4
                            break;
                        }
                        case 119: {
                            // 0x8834
                            *(int32_t *)(i_v7 & -4) = i_v8;
                            // break -> 0x87e4
                            break;
                        }
                        case 98: {
                            // .critedge
                            *(char *)i_v7 = (char)i_v8;
                            // break -> 0x87e4
                            break;
                        }
                        }
                        // 0x87e4
                        sprintf();
                        printf();
                        fflush();
                    }
                    // break -> 0x875c
                    break;
                }
                default: {
                    // 0x86f4
                    fprintf();
                    exit();
                }
                case 104: {
                    // 0x8710
                    i_v7 = i_v6 & -2;
                    // branch (via goto) -> 0x8720
                    goto lab_0x8720;
                }
                }
                // 0x875c
                if (munmap() != -1) {
                    // 0x8770
                    close();
                    return 0;
                }
                // 0x88c4
                __errno_location();
                strerror();
                goto lab_0x8868;
            }
        }
    }
lab_0x8868:
    // 0x8868
    fprintf();
    exit();
    // 0x8880
    fprintf();
    exit();
    // 0x889c
    __errno_location();
    strerror();
    goto lab_0x8868;
}

// Address range: 0x8918 - 0x8948
int32_t entry_point(int32_t i_a1, int32_t i_a2) {
    // 0x8918
    __libc_start_main();
    return abort();
}

// Address range: 0x8954 - 0x8970
int32_t function_8954(void) {
    int32_t i_v1 =
        *(int32_t *)((int32_t)&i_g6 + (int32_t) "printf" + 80); // 0x8960
    if (i_v1 == 0) {
        int32_t i_v2; // 0x8954
        return i_v2;
    }
    // 0x896c
    return function_8598();
}

// Address range: 0x8978 - 0x89a4
int32_t function_8978(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4) {
    // 0x8978
    return &i_g2;
}

// Address range: 0x89b0 - 0x89e4
int32_t function_89b0(int32_t *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x89b0
    return &i_g2;
}

// Address range: 0x89f0 - 0x8a14
int32_t function_89f0(void) {
    // 0x89f0
    int32_t i_v1; // 0x89f0
    if (*(char *)&p_g3 != 0) {
        return i_v1;
    }
    int32_t i_v2 = function_8978(i_v1, i_v1, i_v1, 0); // 0x8a04
    *(char *)&p_g3 = 1;
    return i_v2;
}

// Address range: 0x8a18 - 0x8a44
int32_t function_8a18(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x8a18
    return function_89b0(&i_g1, i_a2, i_a3, i_a4);
}

// Address range: 0x8a4c - 0x8aa8
int32_t function_8a4c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_8530(i_a1, i_a2, i_a3, i_a4); // 0x8a68
    int32_t i_v2 =
        (int32_t)&i_g5 + 0x8a6c - ((int32_t)&i_g7 + (int32_t)&i_g4) >> 2 == 0
            ? i_v1
            : i_a1;
    return i_v2;
}

// Address range: 0x8ab0 - 0x8ab4
int32_t function_8ab0(void) {
    // 0x8ab0
    int32_t i_v1; // 0x8ab0
    return i_v1;
}

// Address range: 0x8ab4 - 0x8abc
int32_t function_8ab4(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x8ab4
    return i_a1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.8.x)
// Detected functions: 28
