/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'godminer_2ea55e8574bcbf89'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct $6ECA53571B8FCC125A3088582131FB6E;
struct sockaddr;
union $1C4035FDEAFFF0FCE26E66A96F6BBEB4;
union $F85E194B51CBDC38F209555F4162D10C;
union $781B27F37A2DA3C5D0084E69F313DC7D;

/* 1 */
struct Elf32_Sym
{
  unsigned __int32 st_name __offset(OFF32,0x19E8C);
  unsigned __int32 st_value __off;
  unsigned __int32 st_size;
  unsigned __int8 st_info;
  unsigned __int8 st_other;
  unsigned __int16 st_shndx;
};

/* 2 */
struct Elf32_Rel
{
  unsigned __int32 r_offset;
  unsigned __int32 r_info;
};

/* 3 */
union Elf32_Dyn::$A263394DDF3EC2D4B1B8448EDD30E249
{
  unsigned __int32 d_val;
  unsigned __int32 d_ptr;
};

/* 4 */
struct Elf32_Dyn
{
  __int32 d_tag;
  union Elf32_Dyn::$A263394DDF3EC2D4B1B8448EDD30E249 d_un;
};

/* 5 */
struct Elf32_Verneed
{
  unsigned __int16 vn_version;
  unsigned __int16 vn_cnt;
  unsigned __int32 vn_file __offset(OFF32,0x19E8C);
  unsigned __int32 vn_aux;
  unsigned __int32 vn_next;
};

/* 6 */
struct Elf32_Vernaux
{
  unsigned __int32 vna_hash;
  unsigned __int16 vna_flags;
  unsigned __int16 vna_other;
  unsigned __int32 vna_name __offset(OFF32,0x19E8C);
  unsigned __int32 vna_next;
};

/* 7 */
typedef struct $6ECA53571B8FCC125A3088582131FB6E fd_set;

/* 9 */
typedef int __fd_mask;

/* 8 */
struct $6ECA53571B8FCC125A3088582131FB6E
{
  __fd_mask __fds_bits[32];
};

/* 11 */
typedef int __time_t;

/* 12 */
typedef int __suseconds_t;

/* 10 */
struct timeval
{
  __time_t tv_sec;
  __suseconds_t tv_usec;
};

/* 13 */
struct sysinfo
{
  int uptime;
  unsigned int loads[3];
  unsigned int totalram;
  unsigned int freeram;
  unsigned int sharedram;
  unsigned int bufferram;
  unsigned int totalswap;
  unsigned int freeswap;
  unsigned __int16 procs;
  unsigned __int16 pad;
  unsigned int totalhigh;
  unsigned int freehigh;
  unsigned int mem_unit;
  char _f[8];
};

/* 16 */
typedef unsigned int __socklen_t;

/* 15 */
typedef __socklen_t socklen_t;

/* 14 */
struct addrinfo
{
  int ai_flags;
  int ai_family;
  int ai_socktype;
  int ai_protocol;
  socklen_t ai_addrlen;
  struct sockaddr *ai_addr;
  char *ai_canonname;
  struct addrinfo *ai_next;
};

/* 18 */
typedef unsigned __int16 sa_family_t;

/* 17 */
struct sockaddr
{
  sa_family_t sa_family;
  char sa_data[14];
};

/* 19 */
struct timespec
{
  __time_t tv_sec;
  int tv_nsec;
};

/* 20 */
typedef unsigned int __useconds_t;

/* 21 */
typedef union $1C4035FDEAFFF0FCE26E66A96F6BBEB4 pthread_cond_t;

/* 23 */
struct $1C4035FDEAFFF0FCE26E66A96F6BBEB4::$20EFCB5FAA72B851457C6BAA266EC02E
{
  int __lock;
  unsigned int __futex;
  unsigned __int64 __total_seq;
  unsigned __int64 __wakeup_seq;
  unsigned __int64 __woken_seq;
  void *__mutex;
  unsigned int __nwaiters;
  unsigned int __broadcast_seq;
};

/* 22 */
union $1C4035FDEAFFF0FCE26E66A96F6BBEB4
{
  struct $1C4035FDEAFFF0FCE26E66A96F6BBEB4::$20EFCB5FAA72B851457C6BAA266EC02E __data;
  char __size[48];
  __int64 __align;
};

/* 24 */
typedef union $F85E194B51CBDC38F209555F4162D10C pthread_mutex_t;

/* 29 */
struct __pthread_internal_slist
{
  struct __pthread_internal_slist *__next;
};

/* 28 */
typedef struct __pthread_internal_slist __pthread_slist_t;

/* 27 */
union $::__pthread_mutex_s::$30DFB618E49C377A3D62C6584A4CBE95
{
  int __spins;
  __pthread_slist_t __list;
};

/* 26 */
struct $F85E194B51CBDC38F209555F4162D10C::__pthread_mutex_s
{
  int __lock;
  unsigned int __count;
  int __owner;
  int __kind;
  unsigned int __nusers;
  union
  {
    int __spins;
    __pthread_slist_t __list;
  };
};

/* 25 */
union $F85E194B51CBDC38F209555F4162D10C
{
  struct $F85E194B51CBDC38F209555F4162D10C::__pthread_mutex_s __data;
  char __size[24];
  int __align;
};

/* 30 */
typedef union $781B27F37A2DA3C5D0084E69F313DC7D pthread_attr_t;

/* 31 */
union $781B27F37A2DA3C5D0084E69F313DC7D
{
  char __size[36];
  int __align;
};

/* 32 */
typedef unsigned int size_t;

/* 34 */
typedef void *__builtin_va_list;

/* 33 */
typedef __builtin_va_list __gnuc_va_list;

/* 35 */
typedef unsigned int pthread_t;

/* 36 */
typedef int (*__compar_fn_t)(const void *, const void *);

/* 38 */
typedef int __jmp_buf[6];

/* 40 */
struct $44840292B0FD4432816E14C2BB6B9957
{
  unsigned int __val[32];
};

/* 39 */
typedef struct $44840292B0FD4432816E14C2BB6B9957 __sigset_t;

/* 37 */
struct __jmp_buf_tag
{
  __jmp_buf __jmpbuf;
  int __mask_was_saved;
  __sigset_t __saved_mask;
};

/* 41 */
union __attribute__((aligned(8))) __n64
{
  unsigned __int64 n64_u64[1];
  unsigned __int32 n64_u32[2];
  unsigned __int16 n64_u16[4];
  unsigned __int8 n64_u8[8];
  __int64 n64_i64[1];
  __int32 n64_i32[2];
  __int16 n64_i16[4];
  __int8 n64_i8[8];
  float n64_f32[2];
  double n64_f64[1];
};

/* 42 */
union __attribute__((aligned(8))) __n128
{
  unsigned __int64 n128_u64[2];
  unsigned __int32 n128_u32[4];
  unsigned __int16 n128_u16[8];
  unsigned __int8 n128_u8[16];
  __int64 n128_i64[2];
  __int32 n128_i32[4];
  __int16 n128_i16[8];
  __int8 n128_i8[16];
  float n128_f32[4];
  double n128_f64[2];
};

/* 43 */
typedef __n64 int8x8_t;

/* 44 */
typedef __n64 uint8x8_t;

/* 45 */
typedef __n64 int16x4_t;

/* 46 */
typedef __n64 int32x2_t;

/* 47 */
typedef __n64 uint16x4_t;

/* 48 */
typedef __n64 uint32x2_t;

/* 49 */
typedef __n128 int8x16_t;

/* 50 */
typedef __n128 int16x8_t;

/* 51 */
typedef __n128 int32x4_t;

/* 52 */
typedef __n128 int64x2_t;

/* 53 */
typedef __n128 uint8x16_t;

/* 54 */
typedef __n128 uint16x8_t;

/* 55 */
typedef __n128 uint32x4_t;

/* 56 */
typedef __n128 uint64x2_t;

/* 57 */
typedef __n64 poly8x8_t;

/* 58 */
typedef __n64 poly16x4_t;

/* 59 */
typedef __n128 poly16x8_t;

/* 60 */
typedef __n128 poly8x16_t;

/* 61 */
typedef __n64 float16x4_t;

/* 62 */
typedef __n64 float32x2_t;

/* 63 */
typedef __n128 float16x8_t;

/* 64 */
typedef __n128 float32x4_t;

/* 65 */
typedef __n128 float64x2_t;

/* 66 */
typedef __n128 poly128_t;

/* 67 */
typedef int16x4_t int16x2_t;

/* 68 */
typedef uint16x4_t uint16x2_t;

/* 69 */
typedef float16x4_t float16x2_t;

/* 70 */
typedef __time_t time_t;

