//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t entry_point(int32_t i_a1, int32_t i_a2);
int32_t function_106e8(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10708(int32_t i_a1);
int32_t function_10714(int32_t i_a1);
int32_t function_10720(int32_t i_a1, int32_t i_a2, int32_t *p_a3, int32_t i_a4,
                       int32_t i_a5, int32_t i_a6, int32_t *p_a7);
int32_t function_1072c(void);
int32_t function_10738(int32_t i_a1);
int32_t function_10744(int32_t *p_a1, int32_t i_a2, int32_t i_a3,
                       int32_t *p_a4);
int32_t function_10750(int32_t i_a1, int32_t *p_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5, int32_t i_a6);
int32_t function_1075c(int32_t i_a1, int32_t i_a2, int32_t i_a3);
int32_t function_10768(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10774(int32_t *p_a1, int32_t *p_a2, int32_t *p_a3,
                       int32_t *p_a4);
int32_t function_10780(int32_t *p_a1);
int32_t function_1078c(int32_t *p_a1, int32_t i_a2, int32_t i_a3,
                       int32_t *p_a4);
int32_t function_10798(int32_t i_a1, char *p_a2, int32_t i_a3, int32_t *p_a4);
int32_t function_107a4(int32_t i_a1, int32_t i_a2);
int32_t function_107b0(int32_t *p_a1, int32_t i_a2);
int32_t function_107bc(char *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_107c8(int32_t i_a1, int32_t i_a2);
int32_t function_107d4(int32_t *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_107e0(void);
int32_t function_107f0(char *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_107fc(int32_t i_a1);
int32_t function_10808(int32_t *p_a1, int32_t i_a2, int32_t i_a3,
                       int32_t *p_a4);
int32_t function_10814(int32_t i_a1);
int32_t function_10820(int32_t *p_a1);
int32_t function_1082c(int32_t *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10868(void);
int32_t function_1088c(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4);
int32_t function_108dc(void);
int32_t function_108f4(int32_t i_a1);
int32_t function_109a8(int32_t *p_a1);
int32_t function_10b9c(void);
int32_t function_10c70(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_10de8(int32_t i_a1, uint32_t i_a2, int32_t i_a3, uint32_t i_a4,
                       uint32_t i_a5, uint32_t i_a6);
int32_t function_11460(int32_t i_a1);
int32_t function_11490(int32_t i_a1);
int32_t function_114c8(uint64_t i_a1, int32_t i_a2);
int32_t function_11514(int64_t i_a1, int32_t i_a2, uint32_t i_a3);
int32_t function_11598(int64_t i_a1, int32_t i_a2, int64_t i_a3, int32_t i_a4,
                       int32_t i_a5, int32_t i_a6);
int32_t function_116c8(int32_t i_a1, uint32_t i_a2);
int32_t function_119ec(int32_t i_a1, int32_t i_a2, int32_t i_a3);
int32_t function_11a04(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5, int32_t i_a6, int32_t i_a7, int32_t i_a8,
                       int32_t i_a9);
int32_t function_11bd0(int32_t i_a1, int32_t i_a2, int32_t i_a3);
int32_t function_11dc8(uint32_t i_a1);
int32_t function_11f50(void);
int32_t function_11f58(int64_t i_a1, int64_t i_a2, int32_t i_a3);
int32_t function_11fbc(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5);
int32_t function_120dc(int32_t *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5);
int32_t function_12180(int32_t i_a1, uint32_t i_a2, int32_t i_a3);
int32_t function_12c34(int32_t i_a1, int32_t i_a2);
int32_t function_12c48(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_1373c(uint32_t i_a1, int32_t i_a2);
int32_t function_13b20(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_13b5c(void);
int32_t function_13b60(int32_t i_a1, int32_t i_a2);
int32_t function_13b64(void);
int32_t function_13b6c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_e0832002(void);
int32_t function_e1a00003(void);
int32_t function_e1a02003(void);
int32_t function_e1a03000(void);
int32_t function_e1a0c002(void);
int32_t function_e1a0e003(void);
int32_t function_e2433004(void);
int32_t function_e243300c(void);
int32_t function_e24b3e51(void);
int32_t function_e3033f1c(void);
int32_t function_e3403001(void);
int32_t function_e58c0000(void);
int32_t function_e58c1004(void);
int32_t function_e58c2008(void);
int32_t function_e58c300c(void);
int32_t function_e8be000f(void);
int32_t function_ea00004f(void);
int32_t function_ebfffdd2(void);
int32_t function_ff86c4c8(void);
int32_t function_ff86c848(void);
int32_t function_ff86ce70(void);
int32_t unknown_240(void);
int32_t unknown_412030(void);
int32_t unknown_413278(void);

// --------------------- Global Variables ---------------------

int32_t i_g1 = 0x108f5; // 0x24f08
int32_t i_g2 = 0;       // 0x25070
int32_t i_g3 = 256;     // 0x2507c
char *p_g4;             // 0x25838
uint32_t i_g5;
int32_t i_g6;

// ------------------------ Functions -------------------------

// Address range: 0x106e8 - 0x106f4
int32_t function_106e8(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x106e8
    return function_10868();
}

// Address range: 0x10708 - 0x10714
int32_t function_10708(int32_t i_a1) {
    // 0x10708
    return function_e24b3e51();
}

// Address range: 0x10714 - 0x10720
int32_t function_10714(int32_t i_a1) {
    // 0x10714
    return function_e2433004();
}

// Address range: 0x10720 - 0x1072c
int32_t function_10720(int32_t i_a1, int32_t i_a2, int32_t *p_a3, int32_t i_a4,
                       int32_t i_a5, int32_t i_a6, int32_t *p_a7) {
    // 0x10720
    return function_e243300c();
}

// Address range: 0x1072c - 0x10738
int32_t function_1072c(void) {
    // 0x1072c
    return function_e1a00003();
}

// Address range: 0x10738 - 0x10744
int32_t function_10738(int32_t i_a1) {
    // 0x10738
    return function_ebfffdd2();
}

// Address range: 0x10744 - 0x10750
int32_t function_10744(int32_t *p_a1, int32_t i_a2, int32_t i_a3,
                       int32_t *p_a4) {
    // 0x10744
    return function_e1a03000();
}

// Address range: 0x10750 - 0x1075c
int32_t function_10750(int32_t i_a1, int32_t *p_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5, int32_t i_a6) {
    // 0x10750
    return function_e1a02003();
}

// Address range: 0x1075c - 0x10768
int32_t function_1075c(int32_t i_a1, int32_t i_a2, int32_t i_a3) {
    // 0x1075c
    return function_e24b3e51();
}

// Address range: 0x10768 - 0x10774
int32_t function_10768(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x10768
    return function_e2433004();
}

// Address range: 0x10774 - 0x10780
int32_t function_10774(int32_t *p_a1, int32_t *p_a2, int32_t *p_a3,
                       int32_t *p_a4) {
    // 0x10774
    return function_e243300c();
}

// Address range: 0x10780 - 0x1078c
int32_t function_10780(int32_t *p_a1) {
    // 0x10780
    return function_e0832002();
}

// Address range: 0x1078c - 0x10798
int32_t function_1078c(int32_t *p_a1, int32_t i_a2, int32_t i_a3,
                       int32_t *p_a4) {
    // 0x1078c
    return function_e3033f1c();
}

// Address range: 0x10798 - 0x107a4
int32_t function_10798(int32_t i_a1, char *p_a2, int32_t i_a3, int32_t *p_a4) {
    // 0x10798
    return function_e3403001();
}

// Address range: 0x107a4 - 0x107b0
int32_t function_107a4(int32_t i_a1, int32_t i_a2) {
    // 0x107a4
    return function_e1a0c002();
}

// Address range: 0x107b0 - 0x107bc
int32_t function_107b0(int32_t *p_a1, int32_t i_a2) {
    // 0x107b0
    return function_e1a0e003();
}

// Address range: 0x107bc - 0x107c8
int32_t function_107bc(char *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x107bc
    return function_e8be000f();
}

// Address range: 0x107c8 - 0x107d4
int32_t function_107c8(int32_t i_a1, int32_t i_a2) {
    // 0x107c8
    return function_e58c0000();
}

// Address range: 0x107d4 - 0x107e0
int32_t function_107d4(int32_t *p_a1, int32_t i_a2, int32_t i_a3,
                       int32_t i_a4) {
    // 0x107d4
    return function_e58c1004();
}

// Address range: 0x107e0 - 0x107f0
int32_t function_107e0(void) {
    // 0x107e0
    return function_e58c2008();
}

// Address range: 0x107f0 - 0x107fc
int32_t function_107f0(char *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x107f0
    return function_e58c300c();
}

// Address range: 0x107fc - 0x10808
int32_t function_107fc(int32_t i_a1) {
    // 0x107fc
    return function_ea00004f();
}

// Address range: 0x10808 - 0x10814
int32_t function_10808(int32_t *p_a1, int32_t i_a2, int32_t i_a3,
                       int32_t *p_a4) {
    // 0x10808
    return function_e24b3e51();
}

// Address range: 0x10814 - 0x10820
int32_t function_10814(int32_t i_a1) {
    // 0x10814
    return function_e2433004();
}

// Address range: 0x10820 - 0x1082c
int32_t function_10820(int32_t *p_a1) {
    // 0x10820
    return function_e243300c();
}

// Address range: 0x1082c - 0x10838
int32_t function_1082c(int32_t *p_a1, int32_t i_a2, int32_t i_a3,
                       int32_t i_a4) {
    // 0x1082c
    return function_e1a00003();
}

// Address range: 0x10838 - 0x10860
int32_t entry_point(int32_t i_a1, int32_t i_a2) {
    // 0x10838
    int32_t i_v1; // 0x10838
    int32_t i_v2 = function_10720(0x1373c, i_a2, &i_v1, 0x13b21, 0x1373c, i_a1,
                                  &i_v1); // 0x10854
    return function_10708(i_v2);
}

// Address range: 0x10868 - 0x10884
int32_t function_10868(void) {
    // 0x10868
    if (i_g2 == 0) {
        int32_t i_v1; // 0x10868
        return i_v1;
    }
    // 0x10880
    return function_1072c();
}

// Address range: 0x1088c - 0x108dc
int32_t function_1088c(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4) {
    // 0x1088c
    int32_t i_v1; // 0x1088c
    int32_t i_v2 = i_v1;
    bool i_v3; // 0x1088c
    if (i_v3) {
        return i_a1;
    }
    bool i_v4; // 0x1088c
    if (!i_v3) {
        int32_t i_v5 = 0x100001 * i_v2 & -1 - 0x400000 * i_v2; // 0x108c4
        i_v4 = i_v5 < 0;
        if (i_v5 == 0) {
            return unknown_240();
        }
    }
    // 0x108d4
    if (i_v4 != i_v3) {
        __asm_svclt(0x4770);
    }
    return i_a1;
}

// Address range: 0x108dc - 0x108f4
int32_t function_108dc(void) {
    // 0x108dc
    int32_t i_v1; // 0x108dc
    if (*(char *)&p_g4 == 0) {
        // 0x108ea
        int32_t i_v2;                                       // 0x108dc
        int32_t i_v3 = function_1088c(i_v2, i_v2, i_v2, 0); // 0x108ea
        *(char *)&p_g4 = 1;
        i_v1 = i_v3;
    }
    // 0x108f2
    return i_v1;
}

// Address range: 0x108f4 - 0x109a8
int32_t function_108f4(int32_t i_a1) {
    int32_t i_v1; // 0x108f4
    function_107f0("Useage:\r", i_v1, i_v1, i_v1);
    function_107bc("\t%s [option] [paramaters]\n\n", i_a1, i_v1, i_v1);
    function_107f0("\tOption:{-f} {-s} {-p} {-n} {-x} {-q}\n", i_a1, i_v1,
                   i_v1);
    function_107f0("\t\t-f [minerType] [fileName] [rootPublicKeyFile]: "
                   "\n\t\t\tOnly Check If Filename was Valided.\n",
                   i_a1, i_v1, i_v1);
    function_107f0(
        "\t\t-s [minerType] [fileName] [rootPublicKeyFile]: \n\t\t\tCheck If "
        "Filename Was Valided, and Splite Bmu To \"/tmp/tmpfw/\"\n",
        i_a1, i_v1, i_v1);
    function_107f0(
        "\t\t-p [minerType] [fileName] [rootPublicKeyFile]: \n\t\t\tCheck If "
        "Filename Was Valided, and Dump BmuComments\n",
        i_a1, i_v1, i_v1);
    function_107f0("\t\t-x [minerType] [fileName] [rootPublicKeyFile]: "
                   "\n\t\t\tCheck If Filename Was FullSize BMU\n",
                   i_a1, i_v1, i_v1);
    function_107f0("\t\t-n [nandBinFile]: \n\t\t\tSplite SigImg To Single File "
                   "To \"/tmp/tmpNand/\"\n",
                   i_a1, i_v1, i_v1);
    function_107f0(
        "\t\t-q: \n\t\t\tGenerate A 256Bytes 0xff File To \"/tmp/256BFF\"\n",
        i_a1, i_v1, i_v1);
    function_107f0("\tReturns:", i_a1, i_v1, i_v1);
    function_107f0("\t\t0: \n\t\t\tWell Done!\n", i_a1, i_v1, i_v1);
    return __asm_nop(function_107f0("\t\tOthers: \n\t\t\tSomething Wrong!\n",
                                    i_a1, i_v1, i_v1));
}

// Address range: 0x109a8 - 0x10b9c
int32_t function_109a8(int32_t *p_a1) {
    int32_t i_v1 = 0; // bp-32788, 0x109d0
    int32_t i_v2;     // bp-32784, 0x109a8
    function_10744(&i_v2, 0, 0x7ffc, &i_v2);
    int32_t i_v3; // bp-32776, 0x109a8
    int32_t i_v4 =
        function_10798((int32_t)p_a1, "rb", 0x7ffc, &i_v3); // 0x109fc
    int32_t i_v5 = 0;                                       // 0x10a0c
    if (i_v4 == 0) {
        // 0x10a10
        function_107f0("Load Nand Image File Failed!", (int32_t) "rb", 0x7ffc,
                       0);
        // 0x10b90
        return 1;
    }
    int32_t i_v6 = 132 * i_v5;                          // 0x10a50
    int32_t *p_v7 = (int32_t *)(i_v6 + (int32_t)&i_g3); // 0x10a58
    function_1082c(&i_v1, *p_v7, 1, i_v4);
    int32_t i_v8 = i_v6 + (int32_t)&i_g3 + 4; // 0x10a94
    int32_t i_v9 =
        function_10798(i_v8, "wb", (int32_t)&i_g3, (int32_t *)i_v8); // 0x10aa4
    int32_t i_v10;                                                   // 0x109a8
    while (i_v9 != 0) {
        // 0x10b08
        function_107d4(&i_v1, *p_v7, 1, i_v9);
        function_10738(i_v9);
        i_v5++;
        if (i_v5 >= 15) {
            // 0x10b84
            function_10738(i_v4);
            i_v10 = 0;
            return i_v10;
        }
        i_v6 = 132 * i_v5;
        p_v7 = (int32_t *)(i_v6 + (int32_t)&i_g3);
        function_1082c(&i_v1, *p_v7, 1, i_v4);
        i_v8 = i_v6 + (int32_t)&i_g3 + 4;
        i_v9 = function_10798(i_v8, "wb", (int32_t)&i_g3, (int32_t *)i_v8);
    }
    // 0x10af8
    function_107bc("Try To Write To File '%s' Failed!\n", i_v8, (int32_t)&i_g3,
                   i_v8);
    function_10738(i_v4);
    i_v10 = 2;
lab_0x10b90:
    // 0x10b90
    return i_v10;
}

// Address range: 0x10b9c - 0x10c70
int32_t function_10b9c(void) {
    // 0x10b9c
    int32_t i_v1; // 0x10b9c
    int32_t i_v2 = function_10798((int32_t) "/tmp/256BFF", "wb", i_v1,
                                  (int32_t *)i_v1); // 0x10bb8
    if (i_v2 == 0) {
        // 0x10bcc
        function_107f0("GenFile Failed!", (int32_t) "wb", i_v1, 0);
        // 0x10c64
        return 1;
    }
    int32_t i_v3 = 0; // bp-272, 0x10be4
    int32_t i_v4;     // bp-268, 0x10b9c
    function_10744(&i_v4, 0, 252, &i_v4);
    for (int32_t i_v5 = 0; i_v5 < 256; i_v5++) {
        // 0x10c10
        *(char *)(i_v5 + (int32_t)&i_v3) = -1;
    }
    // 0x10c3c
    function_107d4(&i_v3, 256, 1, i_v2);
    function_10738(i_v2);
    // 0x10c64
    return 0;
}

// Address range: 0x10c70 - 0x10de8
int32_t function_10c70(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_107a4(i_a4, 1024);    // 0x10ca4
    int32_t i_v2 = function_10768(i_v1, 0, 0, 0); // 0x10cbc
    if (i_v2 == 0) {
        int32_t i_v3 = function_107c8(function_10714(0), 0); // 0x10ce0
        function_107bc("OpenSSL error: %s\n", i_v3, 0, i_v3);
        function_107f0("Read Root PubK Failed!", i_v3, 0, i_v3);
        // 0x10ddc
        return 12;
    }
    // 0x10d0c
    int32_t i_v4; // bp-164, 0x10c70
    function_10820(&i_v4);
    function_10808(&i_v4, i_a1, i_a2, &i_v4);
    int32_t i_v5; // bp-52, 0x10c70
    function_10774(&i_v5, &i_v4, &i_v4, &i_v5);
    int32_t i_v6 = function_10750(672, &i_v5, 32, i_a3, 256, i_v2); // 0x10d60
    int32_t i_v7 = function_107fc(i_v2);                            // 0x10d84
    if (i_v1 != 0) {
        // 0x10d88
        i_v7 = function_10814(i_v1);
    }
    int32_t i_v8 = 0; // 0x10d98
    if (i_v6 != 1) {
        int32_t i_v9 = function_107c8(function_10714(i_v7), 0); // 0x10db4
        function_107bc("OpenSSL error: %s\n", i_v9, 32, i_v9);
        function_107f0("Check miner.pem Failed!", i_v9, 32, i_v9);
        i_v8 = 13;
    }
    // 0x10ddc
    return i_v8;
}

// Address range: 0x10de8 - 0x11460
int32_t function_10de8(int32_t i_a1, uint32_t i_a2, int32_t i_a3, uint32_t i_a4,
                       uint32_t i_a5, uint32_t i_a6) {
    int32_t i_v1 = 0; // bp-1044, 0x10e08
    int32_t i_v2;     // bp-1040, 0x10de8
    function_10744(&i_v2, 0, 1020, &i_v2);
    int32_t i_v3; // bp-1156, 0x10de8
    function_10820(&i_v3);
    int32_t i_v4 = 0; // 0x10e5c
    if (i_a6 % 256 != 0) {
        char *p_v5 = (char *)0x706d742f; // bp-1316, 0x10e78
        int32_t i_v6;                    // bp-1304, 0x10de8
        function_10744(&i_v6, 0, 116, &i_v6);
        i_g5 = i_a4 % 256;
        switch ((char)i_a4) {
        case 0: {
            int32_t i_v7 =
                function_10780((int32_t *)&p_v5) + (int32_t)&p_v5; // 0x10ef4
            *(int32_t *)i_v7 = 0x544f4f42;
            *(int32_t *)(i_v7 + 4) = 0x6e69622e;
            *(char *)(i_v7 + 8) = 0;
            // break -> 0x111b4
            break;
        }
        case 1: {
            int32_t i_v8 =
                function_10780((int32_t *)&p_v5) + (int32_t)&p_v5; // 0x10f40
            *(int32_t *)i_v8 = 0x69766564;
            *(int32_t *)(i_v8 + 4) = 0x72746563;
            *(int32_t *)(i_v8 + 8) = 0x642e6565;
            *(int16_t *)(i_v8 + 12) = 0x6274;
            *(char *)(i_v8 + 14) = 0;
            // break -> 0x111b4
            break;
        }
        case 2: {
            int32_t i_v9 =
                function_10780((int32_t *)&p_v5) + (int32_t)&p_v5; // 0x10f9c
            *(int32_t *)i_v9 = 0x616d4975;
            *(int16_t *)(i_v9 + 4) = 0x6567;
            *(char *)(i_v9 + 6) = 0;
            // break -> 0x111b4
            break;
        }
        case 3: {
            int32_t i_v10 =
                function_10780((int32_t *)&p_v5) + (int32_t)&p_v5; // 0x10fec
            *(int32_t *)i_v10 = 0x656e696d;
            *(int32_t *)(i_v10 + 4) = 0x2e736672;
            *(int32_t *)(i_v10 + 8) = 0x67616d69;
            *(int32_t *)(i_v10 + 12) = 0x7a672e65;
            *(char *)(i_v10 + 16) = 0;
            // break -> 0x111b4
            break;
        }
        case 4: {
            int32_t i_v11 =
                function_10780((int32_t *)&p_v5) + (int32_t)&p_v5; // 0x11048
            *(int32_t *)i_v11 = 0x61647075;
            *(int32_t *)(i_v11 + 4) = 0x692e6574;
            *(int32_t *)(i_v11 + 8) = 0x6567616d;
            *(int32_t *)(i_v11 + 12) = 0x7a672e;
            // break -> 0x111b4
            break;
        }
        case 5: {
            int32_t i_v12 =
                function_10780((int32_t *)&p_v5) + (int32_t)&p_v5; // 0x1109c
            *(int32_t *)i_v12 = 0x2e6c7263;
            *(int32_t *)(i_v12 + 4) = 0x2e726174;
            *(int16_t *)(i_v12 + 8) = 0x7a67;
            *(char *)(i_v12 + 10) = 0;
            // break -> 0x111b4
            break;
        }
        case 6: {
            int32_t i_v13 =
                function_10780((int32_t *)&p_v5) + (int32_t)&p_v5; // 0x110f0
            *(int32_t *)i_v13 = 0x656e696d;
            *(int32_t *)(i_v13 + 4) = 0x74622e72;
            *(int32_t *)(i_v13 + 8) = 0x61742e6d;
            *(int32_t *)(i_v13 + 12) = 0x7a672e72;
            *(char *)(i_v13 + 16) = 0;
            // break -> 0x111b4
            break;
        }
        case 7: {
            int32_t i_v14 =
                function_10780((int32_t *)&p_v5) + (int32_t)&p_v5; // 0x1114c
            *(int32_t *)i_v14 = 0x65736572;
            *(int32_t *)(i_v14 + 4) = 0x657672;
            // break -> 0x111b4
            break;
        }
        case 9: {
            int32_t i_v15 =
                function_10780((int32_t *)&p_v5) + (int32_t)&p_v5; // 0x11190
            *(int32_t *)i_v15 = 0x61746164;
            *(int32_t *)(i_v15 + 4) = 0x656c6966;
            *(char *)(i_v15 + 8) = 0;
            __asm_nop(0x61746164);
            // break -> 0x111b4
            break;
        }
        }
        int32_t i_v16; // 0x10de8
        if (i_a5 % 256 == 0) {
            // 0x111b4
            i_v16 = (int32_t)&p_v5;
        } else {
            int32_t i_v17 = function_10780((int32_t *)&p_v5); // 0x111d0
            int32_t i_v18 = (int32_t)&p_v5;
            int32_t i_v19 = i_v17 + i_v18; // 0x111e8
            *(int32_t *)i_v19 = 0x6769732e;
            *(char *)(i_v19 + 4) = 0;
            i_v16 = i_v18;
        }
        int32_t i_v20 = i_v16;
        function_107bc("fileName:'%s', size:[%d]\r\n", i_v20, i_a2, i_v20);
        int32_t i_v21 =
            function_10798(i_v20, "wb", i_a2, (int32_t *)&p_v5); // 0x1123c
        i_v4 = i_v21;
        if (i_v21 == 0) {
            // 0x11250
            function_107bc("Create File '%s' Failed!\r\n", i_v20, i_a2, i_v20);
            i_v4 = 0;
        }
    }
    int32_t i_v22 = &i_v1;
    int32_t i_v23 = i_a2; // 0x1130c
    if (i_a2 >= 1024 == (i_a2 != 1024)) {
        int32_t i_v24 = 0;                                    // 0x1129c
        int32_t i_v25 = function_1082c(&i_v1, 1, 1024, i_a1); // 0x11288
        function_10808(&i_v3, i_v22, 1024, &i_v3);
        if (i_a6 % 256 != 0 && i_v4 != 0) {
            // 0x112e0
            function_107d4(&i_v1, 1, 1024, i_v4);
        }
        // 0x112fc
        i_v24 += i_v25;
        int32_t i_v26 = i_a2 - i_v24; // 0x11304
        i_v23 = i_v26;
        while (i_v26 >= 1024 == (i_v26 != 1024)) {
            // 0x11270
            i_v25 = function_1082c(&i_v1, 1, 1024, i_a1);
            function_10808(&i_v3, i_v22, 1024, &i_v3);
            if (i_a6 % 256 != 0 && i_v4 != 0) {
                // 0x112e0
                function_107d4(&i_v1, 1, 1024, i_v4);
            }
            // 0x112fc
            i_v24 += i_v25;
            i_v26 = i_a2 - i_v24;
            i_v23 = i_v26;
        }
    }
    int32_t i_v27 = function_1082c(&i_v1, 1, i_v23, i_a1); // 0x11330
    function_10808(&i_v3, i_v22, i_v27, &i_v3);
    int32_t i_v28; // bp-1188, 0x10de8
    if (i_a6 % 256 == 0 || i_v4 == 0) {
        // 0x11394
        i_v28 = 0;
        function_10774(&i_v28, &i_v3, &i_v3, &i_v28);
    } else {
        // 0x11404
        function_107d4(&i_v1, 1, i_v27, i_v4);
        i_v28 = 0;
        function_10774(&i_v28, &i_v3, &i_v3, &i_v28);
        function_10738(i_v4);
    }
    // 0x11414
    *(int32_t *)i_a3 = i_v28;
    *(int32_t *)(i_a3 + 4) = 0;
    *(int32_t *)(i_a3 + 8) = 0;
    *(int32_t *)(i_a3 + 12) = 0;
    *(int32_t *)(i_a3 + 16) = 0;
    *(int32_t *)(i_a3 + 20) = 0;
    *(int32_t *)(i_a3 + 24) = 0;
    *(int32_t *)(i_a3 + 28) = 0;
    __asm_nop(0);
    return 0;
}

// Address range: 0x11460 - 0x11490
int32_t function_11460(int32_t i_a1) {
    // 0x11460
    return i_a1;
}

// Address range: 0x11490 - 0x114c8
int32_t function_11490(int32_t i_a1) {
    // 0x11490
    int64_t i_v1; // bp-16, 0x11490
    function_1078c((int32_t *)&i_v1, i_a1, 8, (int32_t *)&i_v1);
    return (0x100000000 * i_v1 >> 32) / 0x100000000;
}

// Address range: 0x114c8 - 0x11514
int32_t function_114c8(uint64_t i_a1, int32_t i_a2) {
    // 0x114c8
    return ((int64_t)(0x100000000 * i_a1) >> 32) / 0x100000000 ^
           i_a1 / 0x8000 % 0x20000;
}

// Address range: 0x11514 - 0x11598
int32_t function_11514(int64_t i_a1, int32_t i_a2, uint32_t i_a3) {
    uint64_t i_v1 = 0x100000000 * i_a1 >> 32;      // 0x11528
    uint32_t i_v2 = (int32_t)i_v1;                 // 0x11528
    uint32_t i_v3 = (int32_t)(i_v1 / 0x100000000); // 0x11528
    return i_v2 >> i_a3 - 32 | i_v2 << 32 - i_a3 | i_v3 >> i_a3 |
           i_v3 << -i_a3 % 64;
}

// Address range: 0x11598 - 0x116c8
int32_t function_11598(int64_t i_a1, int32_t i_a2, int64_t i_a3, int32_t i_a4,
                       int32_t i_a5, int32_t i_a6) {
    int32_t i_v1 = i_a3;
    int32_t i_v2 =
        ((i_v1 >> 31 ^ (int32_t)((0x100000000 * i_a1 >> 32) / 0x100000000)) *
             i_a5 ^
         i_v1) /
        0x80000000 * i_a5; // 0x11640
    return (i_v2 >> 31 ^ i_v2 / 0x8000) * i_a5 / 0x80000000;
}

// Address range: 0x116c8 - 0x119ec
int32_t function_116c8(int32_t i_a1, uint32_t i_a2) {
    // 0x116c8
    if (i_a2 != 7 && i_a2 >= 7) {
        int32_t i_v1 = (2 * i_a2 - 0x651e95c5) / 0x80000000;
        int32_t i_v2 = function_11490(i_a1) - 0x651e95c5 >> 31;
        int32_t i_v3 = function_11490(i_a2 + i_a1 - 8); // 0x11754
        int32_t i_v4 = i_v3 >> 31;
        int32_t i_v5 =
            function_11514((int64_t)i_v4, i_v3, 37) * i_v1 + i_v2 >> 31;
        int32_t i_v6 =
            (function_11514((int64_t)i_v2, i_v2, 25) + i_v4) * i_v1; // 0x117e0
        // 0x119dc
        return function_11598((int64_t)i_v5, i_v5, (int64_t)(i_v6 >> 31), i_v6,
                              i_v1, i_v1);
    }
    if (i_a2 != 3 && i_a2 >= 3) {
        int32_t i_v7 = 2 * i_a2 - 0x651e95c5;           // 0x11838
        int32_t i_v8 = 8 * function_11460(i_a1) + i_a2; // 0x11878
        // 0x119dc
        return function_11598((int64_t)(i_v8 >> 31), i_v8,
                              (int64_t)function_11460(i_a2 + i_a1 - 4), 0,
                              i_v7 >> 31, i_v7);
    }
    int32_t i_v9 = -0x651e95c5; // 0x118d8
    if (i_a2 != 0) {
        unsigned char i_v10 = *(char *)(i_a2 / 2 + i_a1); // 0x118f8
        unsigned char i_v11 = *(char *)(i_a2 + i_a1 - 1); // 0x11910
        int32_t i_v12;                                    // 0x116c8
        int32_t i_v13 = -0x3c5a37a4 * (4 * (int32_t)i_v11 + i_a2) ^
                        -0x651e95c5 * (256 * (int32_t)i_v10 |
                                       (uint32_t)i_v12 % 256); // 0x11998
        i_v9 = -0x651e95c5 * function_114c8((int64_t)(i_v13 >> 31), i_v13);
    }
    // 0x119dc
    return i_v9;
}

// Address range: 0x119ec - 0x11a02
int32_t function_119ec(int32_t i_a1, int32_t i_a2, int32_t i_a3) {
    int32_t i_v1 = unknown_412030();       // 0x119ec
    int32_t i_v2 = *(int32_t *)(i_v1 + 4); // 0x119fc
    int32_t i_v3 = i_v1 + 16;              // 0x119fc
    *(int32_t *)i_v2 = i_v3;
    *(int32_t *)(i_v2 + 4) = *(int32_t *)i_v1;
    int32_t i_v4; // 0x119ec
    *(int32_t *)(i_v2 + 12) = i_v4 ^ i_a2;
    return i_v3;
}

// Address range: 0x11a04 - 0x11bd0
int32_t function_11a04(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5, int32_t i_a6, int32_t i_a7, int32_t i_a8,
                       int32_t i_a9) {
    int32_t i_v1 = 2 * i_a2 - 0x651e95c5;    // 0x11a2c
    int32_t i_v2 = function_11490(i_a1);     // 0x11a3c
    int32_t i_v3 = function_11490(i_a1 + 8); // 0x11a74
    int32_t i_v4 = i_a2 + i_a1;
    int32_t i_v5 = function_11490(i_v4 - 8) * i_v1; // 0x11aac
    int32_t i_v6 = function_11490(i_v4 - 16);       // 0x11ad4
    int32_t i_v7 = -0x4b6d4991 * i_v2 >> 31;
    int32_t i_v8 = i_v3 >> 31;
    int32_t i_v9 = i_v7 + i_v8;                                      // 0x11b08
    int32_t i_v10 = function_11514((int64_t)(i_v9 >> 31), i_v9, 43); // 0x11b20
    int32_t i_v11 = i_v5 >> 31;
    int32_t i_v12 = function_11514((int64_t)i_v11, i_v5, 30) + i_v10 +
                    (-0x651e95c5 * i_v6 >> 31); // 0x11b4c
    int32_t i_v13 = i_v8 - 0x651e95c5;          // 0x11b68
    int32_t i_v14 =
        i_v11 + i_v7 +
        function_11514((int64_t)(i_v13 >> 31), i_v13, 18); // 0x11b94
    return function_11598((int64_t)(i_v12 >> 31), i_v12, (int64_t)(i_v14 >> 31),
                          i_v14, i_v1 >> 31, i_v1);
}

// Address range: 0x11bd0 - 0x11dc4
int32_t function_11bd0(int32_t i_a1, int32_t i_a2, int32_t i_a3) {
    // 0x11bd0
    int32_t i_v1; // 0x11bd0
    bool i_v2;    // 0x11bd0
    if (i_v2) {
        __asm_svchs(0x90404f);
        i_v1 = i_a1;
        if (i_v2) {
            // .thread
            i_v1 = function_ff86c4c8();
            goto lab_0x11bd8;
        } else {
            goto lab_0x11bd8;
        }
    } else {
        // .thread
        i_v1 = function_ff86c4c8();
        goto lab_0x11bd8;
    }
lab_0x11bd8:;
    int32_t i_v3 = 2 * i_a2 - 0x651e95c5;    // 0x11c0c
    int32_t i_v4 = function_11490(i_v1);     // 0x11c1c
    int32_t i_v5 = function_11490(i_v1 + 8); // 0x11c54
    int32_t i_v6 = i_v1 + i_a2;
    int32_t i_v7 = function_11490(i_v6 - 8) * i_v3; // 0x11c8c
    int32_t i_v8 = function_11490(i_v6 - 16);       // 0x11cb4
    int32_t i_v9 = -0x651e95c5 * i_v4 >> 31;
    int32_t i_v10 = i_v5 >> 31;
    int32_t i_v11 = i_v9 + i_v10; // 0x11ce8
    int32_t i_v12 =
        function_11514((int64_t)(i_v11 >> 31), i_v11, 43); // 0x11d00
    int32_t i_v13 = i_v7 >> 31;
    int32_t i_v14 = (function_11514((int64_t)i_v13, i_v7, 30) + i_v12 +
                     (-0x651e95c5 * i_v8 >> 31)) /
                    0x80000000;
    int32_t i_v15 = i_v10 - 0x651e95c5; // 0x11d50
    int32_t i_v16 =
        i_v13 + i_v9 +
        function_11514((int64_t)(i_v15 >> 31), i_v15, 18); // 0x11d7c
    function_11598((int64_t)i_v14, i_v14, (int64_t)(i_v16 >> 31), i_v16,
                   i_v3 >> 31, i_v3);
    return function_11490(i_v1 + 16);
}

// Address range: 0x11dc8 - 0x11f50
int32_t function_11dc8(uint32_t i_a1) {
    // 0x11dc8
    int32_t i_v1;                                        // 0x11dc8
    int32_t *p_v2 = (int32_t *)(i_v1 - 36);              // 0x11dc8
    uint64_t i_v3 = (int64_t)*p_v2 * (int64_t)i_a1;      // 0x11dcc
    int32_t i_v4 = i_v1 + (int32_t)(i_v3 / 0x100000000); // 0x11dd0
    int32_t i_v5 = i_v1 - 92;                            // 0x11dd8
    *(int32_t *)i_v5 = (int32_t)i_v3;
    *(int32_t *)(i_v1 - 88) = i_v4;
    int32_t *p_v6 = (int32_t *)(i_v1 - 120);   // 0x11de0
    int32_t i_v7 = function_11490(*p_v6 + 24); // 0x11dec
    int32_t i_v8 = i_v1 - 100;                 // 0x11df0
    *(int32_t *)i_v8 = i_v7;
    *(int32_t *)(i_v1 - 96) = i_v4;
    int32_t *p_v9 = (int32_t *)(i_v1 - 124);                 // 0x11df4
    uint32_t i_v10 = function_11490(*p_v9 - 32 + *p_v6);     // 0x11e08
    uint64_t i_v11 = *(int64_t *)(i_v1 - 76);                // 0x11e0c
    uint32_t i_v12 = i_v10 + (int32_t)(i_v11 / 0x100000000); // 0x11e10
    int32_t i_v13 = i_v1 - 156;                              // 0x11e14
    *(int32_t *)i_v13 = i_v12;
    *(int32_t *)(i_v1 - 152) = i_v4 + (int32_t)i_v11 + (int32_t)(i_v12 < i_v10);
    int32_t *p_v14 = (int32_t *)(i_v1 - 32); // 0x11e20
    int32_t i_v15 = *p_v14;                  // 0x11e20
    uint64_t i_v16 = *(int64_t *)i_v13;      // 0x11e24
    uint64_t i_v17 = i_v16 / 0x100000000;    // 0x11e24
    uint32_t i_v18 = *p_v2;                  // 0x11e30
    uint64_t i_v19 = i_v17 * (int64_t)i_v18; // 0x11e48
    int32_t i_v20 = i_v15 * (int32_t)i_v17 + i_v18 * (int32_t)i_v16 +
                    (int32_t)(i_v19 / 0x100000000); // 0x11e4c
    int32_t i_v21 = i_v1 - 108;                     // 0x11e54
    *(int32_t *)i_v21 = (int32_t)i_v19;
    *(int32_t *)(i_v1 - 104) = i_v20;
    uint32_t i_v22 = function_11490(*p_v9 - 24 + *p_v6);     // 0x11e70
    uint64_t i_v23 = *(int64_t *)(i_v1 - 84);                // 0x11e74
    uint32_t i_v24 = i_v22 + (int32_t)(i_v23 / 0x100000000); // 0x11e78
    int32_t i_v25 = i_v1 - 164;                              // 0x11e7c
    *(int32_t *)i_v25 = i_v24;
    *(int32_t *)(i_v1 - 160) =
        i_v20 + (int32_t)i_v23 + (int32_t)(i_v24 < i_v22);
    int32_t i_v26 = *p_v14;                  // 0x11e88
    uint64_t i_v27 = *(int64_t *)i_v25;      // 0x11e8c
    uint64_t i_v28 = i_v27 / 0x100000000;    // 0x11e8c
    uint32_t i_v29 = *p_v2;                  // 0x11e98
    uint64_t i_v30 = i_v28 * (int64_t)i_v29; // 0x11eb0
    int32_t i_v31 = i_v1 - 116;              // 0x11ebc
    *(int32_t *)i_v31 = (int32_t)i_v30;
    *(int32_t *)(i_v1 - 112) = i_v26 * (int32_t)i_v28 + i_v29 * (int32_t)i_v27 +
                               (int32_t)(i_v30 / 0x100000000);
    uint64_t i_v32 = *(int64_t *)i_v5;                       // 0x11ec4
    uint32_t i_v33 = (int32_t)(i_v32 / 0x100000000);         // 0x11ec4
    int64_t *p_v34 = (int64_t *)i_v8;                        // 0x11ec8
    uint64_t i_v35 = *p_v34;                                 // 0x11ec8
    uint32_t i_v36 = (int32_t)(i_v35 / 0x100000000) + i_v33; // 0x11ecc
    int32_t i_v37 = i_v1 - 172;                              // 0x11ed0
    *(int32_t *)i_v37 = i_v36;
    *(int32_t *)(i_v1 - 168) =
        (int32_t)i_v35 + (int32_t)i_v32 + (int32_t)(i_v36 < i_v33);
    int64_t i_v38 = *(int64_t *)i_v37;                               // 0x11ee0
    int32_t i_v39 = i_v38;                                           // 0x11ee0
    uint32_t i_v40 = function_11514(i_v38 >> 32, i_v39, 43);         // 0x11ee4
    int64_t i_v41 = *(int64_t *)i_v21;                               // 0x11ef4
    int32_t i_v42 = i_v41;                                           // 0x11ef4
    uint32_t i_v43 = function_11514(i_v41 >> 32, i_v42, 30) + i_v40; // 0x11f04
    int32_t i_v44 = i_v1 - 180;                                      // 0x11f08
    *(int32_t *)i_v44 = i_v43;
    *(int32_t *)(i_v1 - 176) = i_v42 + i_v39 + (int32_t)(i_v43 < i_v40);
    uint64_t i_v45 = *(int64_t *)i_v31;                      // 0x11f14
    uint64_t i_v46 = *(int64_t *)i_v44;                      // 0x11f18
    uint32_t i_v47 = (int32_t)(i_v46 / 0x100000000);         // 0x11f18
    uint32_t i_v48 = i_v47 + (int32_t)(i_v45 / 0x100000000); // 0x11f20
    *(int32_t *)(i_v1 - 188) = i_v48;
    *(int32_t *)(i_v1 - 184) =
        (int32_t)i_v46 + (int32_t)i_v45 + (int32_t)(i_v48 < i_v47);
    uint64_t i_v49 = *p_v34;                                 // 0x11f30
    int32_t i_v50 = i_v49;                                   // 0x11f30
    int32_t i_v51 = i_v49 / 0x100000000;                     // 0x11f30
    uint64_t i_v52 = *(int64_t *)(i_v1 - 44);                // 0x11f34
    uint32_t i_v53 = (int32_t)(i_v52 / 0x100000000) + i_v51; // 0x11f38
    *(int32_t *)(i_v1 - 196) = i_v53;
    *(int32_t *)(i_v1 - 192) =
        (int32_t)i_v52 + i_v50 + (int32_t)(i_v53 < i_v51);
    return function_11f58((int64_t)i_v51, (int64_t)i_v50, 18);
}

// Address range: 0x11f50 - 0x11f58
int32_t function_11f50(void) {
    // 0x11f50
    bool i_v1; // 0x11f50
    if (i_v1) {
        __asm_svchs(0x90404f);
    }
    int32_t i_v2; // 0x11f50
    return i_v2;
}

// Address range: 0x11f58 - 0x11fbc
int32_t function_11f58(int64_t i_a1, int64_t i_a2, int32_t i_a3) {
    // 0x11f58
    int32_t i_v1;                                           // 0x11f58
    int64_t i_v2 = *(int64_t *)(i_v1 - 196);                // 0x11f58
    int32_t i_v3 = i_v2;                                    // 0x11f58
    uint32_t i_v4 = function_11514(i_v2 >> 32, i_v3, i_a3); // 0x11f5c
    uint64_t i_v5 = *(int64_t *)(i_v1 - 92);                // 0x11f60
    uint32_t i_v6 = i_v4 + (int32_t)(i_v5 / 0x100000000);   // 0x11f64
    int32_t i_v7 = i_v1 - 204;                              // 0x11f68
    *(int32_t *)i_v7 = i_v6;
    *(int32_t *)(i_v1 - 200) = (int32_t)i_v5 + i_v3 + (int32_t)(i_v6 < i_v4);
    uint64_t i_v8 = *(int64_t *)(i_v1 - 108);               // 0x11f74
    uint64_t i_v9 = *(int64_t *)i_v7;                       // 0x11f78
    uint32_t i_v10 = (int32_t)(i_v9 / 0x100000000);         // 0x11f78
    uint32_t i_v11 = i_v10 + (int32_t)(i_v8 / 0x100000000); // 0x11f80
    int32_t i_v12 = i_v1 - 212;                             // 0x11f84
    *(int32_t *)i_v12 = i_v11;
    *(int32_t *)(i_v1 - 208) =
        (int32_t)i_v9 + (int32_t)i_v8 + (int32_t)(i_v11 < i_v10);
    uint64_t i_v13 = *(int64_t *)(i_v1 - 36); // 0x11f90
    int64_t i_v14 = *(int64_t *)i_v12;        // 0x11f98
    int64_t i_v15 = *(int64_t *)(i_v1 - 188); // 0x11f9c
    return function_11598(i_v15 >> 32, (int32_t)i_v15, i_v14 >> 32,
                          (int32_t)i_v14, (int32_t)(i_v13 / 0x100000000),
                          (int32_t)i_v13);
}

// Address range: 0x11fbc - 0x120dc
int32_t function_11fbc(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5) {
    // 0x11fbc
    int64_t i_v1; // 0x11fbc
    int32_t i_v2 =
        ((i_a3 >> 31) + (int32_t)(i_v1 / 0x100000000)) / 0x80000000; // 0x11fe8
    int32_t i_v3 = i_v1 / 0x100000000;                               // 0x11ff4
    int32_t i_v4 = (int32_t)(i_v1 / 0x100000000) + i_v3 + i_v2;      // 0x11ff8
    int32_t i_v5 = function_11514((int64_t)(i_v4 >> 31), i_v4, 21);  // 0x12010
    int32_t i_v6 = (i_v2 + (i_a5 >> 31)) / 0x80000000 +
                       (int32_t)((uint64_t)i_v1 / 0x100000000) >>
                   31;
    uint32_t i_v7 =
        ((i_v5 >> 31) + function_11514((int64_t)i_v6, i_v6, 44)) / 0x80000000;
    int32_t i_v8 = i_v6 + i_v3;  // 0x12090
    uint32_t i_v9 = i_v7 + i_v2; // 0x120b0
    *(int32_t *)i_a1 = i_v8 >> 31;
    *(int32_t *)(i_a1 + 4) = i_v8;
    *(int32_t *)(i_a1 + 8) = i_v9;
    *(int32_t *)(i_a1 + 12) = i_v9 + (int32_t)(i_v9 < i_v7);
    return i_a1;
}

// Address range: 0x120dc - 0x12180
int32_t function_120dc(int32_t *p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4,
                       int32_t i_a5) {
    int32_t i_v1 = (int32_t)p_a1;
    int32_t i_v2 = function_11490(i_a2);     // 0x120f8
    int32_t i_v3 = function_11490(i_a2 + 8); // 0x12110
    function_11490(i_a2 + 16);
    function_11490(i_a2 + 24);
    function_11fbc(i_v1, i_a2, i_v2, i_a2, i_v3);
    return i_v1;
}

// Address range: 0x12180 - 0x12c34
int32_t function_12180(int32_t i_a1, uint32_t i_a2, int32_t i_a3) {
    // 0x12180
    if (i_a2 >= 16 != i_a2 != 16) {
        // 0x12c24
        return function_116c8(i_a1, i_a2);
    }
    // 0x121c4
    if (i_a2 >= 32 != i_a2 != 32 || i_a2 >= 64 != i_a2 != 64) {
        // 0x12c24
        return i_a1;
    }
    int32_t i_v1 = function_114c8(0x413964a1, -0x709bf205); // 0x12288
    int64_t i_v2 = 0;                                       // bp-96, 0x122bc
    int64_t i_v3 = 0;                                       // bp-112, 0x122d4
    int32_t i_v4 = function_11490(i_a1);                    // 0x12314
    int32_t i_v5 = (i_a2 - 1 & -64) + i_a1;                 // 0x1233c
    i_v2 = 0;
    int32_t i_v6 = i_a1;       // 0x1235c
    int32_t i_v7 = i_v4 >> 31; // 0x1235c
    int32_t i_v8 = 0;          // 0x1235c
    int32_t i_v9 = ((i_v8 + i_v7 >> 31) +
                    (int32_t)((0x100000000 * i_v2 >> 32) / 0x100000000)) /
                       0x80000000 +
                   function_11490(i_v6 + 8);                         // 0x123b4
    int32_t i_v10 = function_11514((int64_t)(i_v9 >> 31), i_v9, 37); // 0x123cc
    int32_t i_v11 = function_11490(i_v6 + 48) + i_v8;                // 0x12430
    int32_t i_v12 =
        function_11514((int64_t)(i_v11 >> 31), i_v11, 42); // 0x12448
    int32_t i_v13 = -0x4b6d4991 * i_v10 >> 31;
    i_v8 = ((function_11490(i_v6 + 40) +
                 (int32_t)((0x100000000 * i_v2 >> 32) / 0x100000000) >>
             31) +
            (-0x4b6d4991 * i_v12 >> 31)) /
           0x80000000;
    int32_t i_v14 =
        (-0x651e95c5 * i_v1 >> 31) +
        (int32_t)((0x100000000 * i_v3 >> 32) / 0x100000000); // 0x124f8
    int32_t i_v15 = -0x4b6d4991 * function_11514((int64_t)(i_v14 >> 31), i_v14,
                                                 33); // 0x12528
    function_120dc(
        (int32_t *)&i_v2, i_v6, 0, 0,
        i_v13 + (int32_t)((0x100000000 * i_v3 >> 32) / 0x100000000) >> 31);
    int32_t i_v16 = i_v15 >> 31;               // 0x125bc
    int32_t i_v17 = function_11490(i_v6 + 16); // 0x125dc
    function_120dc((int32_t *)&i_v3, i_v6 + 32, i_v16, i_v16,
                   i_v8 + i_v17 >> 31);
    int32_t i_v18 =
        (0x100000000 * (int64_t)(i_v15 ^ i_v13) >> 63) / 0x100000000; // 0x12628
    i_v7 = (i_v13 ^ i_v18) >> 31;
    int32_t i_v19 = (i_v7 ^ i_v18) >> 31;
    i_v6 += 64;
    while (i_v6 != i_v5) {
        i_v9 = ((i_v8 + i_v7 >> 31) +
                (int32_t)((0x100000000 * i_v2 >> 32) / 0x100000000)) /
                   0x80000000 +
               function_11490(i_v6 + 8);
        i_v10 = function_11514((int64_t)(i_v9 >> 31), i_v9, 37);
        i_v11 = function_11490(i_v6 + 48) + i_v8;
        i_v12 = function_11514((int64_t)(i_v11 >> 31), i_v11, 42);
        i_v13 = -0x4b6d4991 * i_v10 >> 31;
        i_v8 = ((function_11490(i_v6 + 40) +
                     (int32_t)((0x100000000 * i_v2 >> 32) / 0x100000000) >>
                 31) +
                (-0x4b6d4991 * i_v12 >> 31)) /
               0x80000000;
        i_v14 = i_v19 + (int32_t)((0x100000000 * i_v3 >> 32) / 0x100000000);
        i_v15 = -0x4b6d4991 * function_11514((int64_t)(i_v14 >> 31), i_v14, 33);
        function_120dc(
            (int32_t *)&i_v2, i_v6, 0, 0,
            i_v13 + (int32_t)((0x100000000 * i_v3 >> 32) / 0x100000000) >> 31);
        i_v16 = i_v15 >> 31;
        i_v17 = function_11490(i_v6 + 16);
        function_120dc((int32_t *)&i_v3, i_v6 + 32, i_v16, i_v16,
                       i_v8 + i_v17 >> 31);
        i_v18 = (0x100000000 * (int64_t)(i_v15 ^ i_v13) >> 63) / 0x100000000;
        i_v7 = (i_v13 ^ i_v18) >> 31;
        i_v19 = (i_v7 ^ i_v18) >> 31;
        i_v6 += 64;
    }
    int32_t i_v20 = (i_a2 + 63) % 64 - 63 + i_v5;             // 0x12358
    int32_t i_v21 = (0x100000000 * i_v3 >> 63) / 0x100000000; // 0x1274c
    int32_t i_v22 =
        (int32_t)((0x100000000 * i_v2 >> 32) / 0x100000000) + i_v21 >> 31;
    i_v2 = i_v22;
    i_v3 = i_v22 + i_v21 >> 31;
    int32_t i_v23 = (i_v22 + (i_v7 + i_v8 >> 31)) / 0x80000000 +
                    function_11490(i_v20 + 8); // 0x127e0
    int32_t i_v24 =
        function_11514((int64_t)(i_v23 >> 31), i_v23, 37); // 0x127fc
    int32_t i_v25 = function_11490(i_v20 + 48) + i_v8;     // 0x12868
    int32_t i_v26 =
        function_11514((int64_t)(i_v25 >> 31), i_v25, 42); // 0x12884
    int32_t i_v27 = -1 * i_v24 >> 31;
    uint64_t i_v28 = (0x100000000 * i_v2 >> 32) / 0x100000000; // 0x12918
    int32_t i_v29 = ((8 * (int32_t)i_v28 + (int32_t)i_v28 >> 31) +
                     function_11490(i_v20 + 40)) /
                            0x80000000 +
                        (-1 * i_v26 >> 31) >>
                    31;
    int32_t i_v30 =
        i_v19 + (int32_t)((0x100000000 * i_v3 >> 32) / 0x100000000); // 0x129b8
    int32_t i_v31 =
        function_11514((int64_t)(i_v30 >> 31), i_v30, 33); // 0x129d4
    int64_t i_v32;                                         // bp-136, 0x12180
    function_120dc(
        (int32_t *)&i_v32, i_v20, 0, 0,
        i_v27 + (int32_t)((0x100000000 * i_v3 >> 32) / 0x100000000) >> 31);
    i_v2 = 0x100000000 * i_v32 >> 32;
    int32_t i_v33 = -1 * i_v31 >> 31;
    int32_t i_v34 = function_11490(i_v20 + 16); // 0x12aa0
    function_120dc((int32_t *)&i_v32, i_v20 + 32, i_v33, i_v33,
                   i_v29 + i_v34 >> 31);
    int64_t i_v35 = 0x100000000 * i_v32;
    i_v3 = i_v35 >> 32;
    int64_t i_v36 = i_v2; // 0x12b54
    int32_t i_v37 =
        function_11598(0x100000000 * i_v36 >> 63, (int32_t)i_v36, i_v35 >> 63,
                       (int32_t)i_v32, -1, -1); // 0x12b6c
    int32_t i_v38 =
        (-0x3c5a37a4 * function_114c8((int64_t)i_v29, i_v29) + i_v37 >> 31) +
        i_v27;                                 // 0x12bc0
    int64_t i_v39;                             // 0x12180
    int32_t i_v40 = i_v39;                     // 0x12bd0
    int64_t i_v41 = 0x100000000 * i_v39 >> 63; // 0x12be8
    int32_t i_v42 =
        function_11598(i_v41, i_v40, i_v41, i_v40, -1, -1) + i_v33; // 0x12bf0
    // 0x12c24
    return function_11598((int64_t)(i_v38 >> 31), i_v38, (int64_t)(i_v42 >> 31),
                          i_v42, -1, -1);
}

// Address range: 0x12c34 - 0x12c42
int32_t function_12c34(int32_t i_a1, int32_t i_a2) {
    int32_t i_v1 = unknown_413278();       // 0x12c34
    int32_t i_v2 = *(int32_t *)(i_v1 + 4); // 0x12c3c
    *(int32_t *)i_v2 = i_v1 + 16;
    *(int32_t *)(i_v2 + 4) = *(int32_t *)i_v1;
    return -0x1d724ffc;
}

// Address range: 0x12c48 - 0x1373c
int32_t function_12c48(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x12c48
    int32_t i_v1;                             // 0x12c48
    int32_t *p_v2 = (int32_t *)(i_v1 - 3064); // 0x12c50
    *p_v2 = i_a1;
    int32_t *p_v3 = (int32_t *)(i_v1 - 3068); // 0x12c54
    *p_v3 = i_a2;
    int32_t *p_v4 = (int32_t *)(i_v1 - 3072); // 0x12c58
    *p_v4 = i_a3;
    int32_t *p_v5 = (int32_t *)(i_v1 - 3076); // 0x12c5c
    *p_v5 = i_a4;
    function_13b60(*p_v2, i_v1 - 196);
    uint32_t i_v6 =
        (int32_t)(*(int64_t *)(i_v1 - 148) / 0x100000000); // 0x12c70
    int32_t *p_v7 = (int32_t *)(i_v1 - 32);                // 0x12c78
    *p_v7 = i_v6;
    int32_t i_v8 = *p_v2;
    if (i_v6 <= 2047) {
        // 0x12c88
        function_107bc("File '%s' Not Enough %d, Something Wrong!\n", i_v8,
                       2048, i_v6);
        // 0x13730
        return 6;
    }
    int32_t i_v9 = function_10798(i_v8, "rb", i_v6, (int32_t *)i_v6); // 0x12cb0
    int32_t *p_v10 = (int32_t *)(i_v1 - 36);                          // 0x12cb4
    *p_v10 = i_v9;
    if (i_v9 == 0) {
        // 0x12cc4
        function_107bc("Read File '%s' Failed!\n", *p_v2, i_v6, 0);
        // 0x13730
        return 7;
    }
    // 0x12cdc
    function_1082c((int32_t *)*p_v5, 2048, 1, i_v9);
    unsigned char i_v11 = *(char *)*p_v5; // 0x12cf4
    int32_t i_v12 = i_v11;                // 0x12cf4
    if (i_v11 != 38) {
        // 0x12d00
        function_107bc("'%s' Not A Btmu File!\n", *p_v2, 1, i_v12);
        int32_t i_v13 = *p_v10; // 0x12d10
        if (i_v13 != 0) {
            // 0x12d1c
            function_10738(i_v13);
        }
        // 0x13730
        return 8;
    }
    // 0x12d2c
    function_107bc("miner_type %s\n", *p_v3, 1, i_v12);
    int32_t i_v14 = function_10780((int32_t *)*p_v3); // 0x12d40
    int32_t i_v15 = function_12180(*p_v3, i_v14, 1);  // 0x12d50
    int32_t i_v16 = i_v1 - 44;                        // 0x12d54
    *(int32_t *)i_v16 = i_v15;
    *(int32_t *)(i_v1 - 40) = i_v14;
    int32_t i_v17 = *p_v5 + 2;         // 0x12d5c
    int32_t i_v18 = i_v1 - 204;        // 0x12d60
    int32_t *p_v19 = (int32_t *)i_v18; // 0x12d6c
    function_1078c(p_v19, i_v17, 8, p_v19);
    int64_t *p_v20 = (int64_t *)i_v16; // 0x12d78
    uint64_t i_v21 = *p_v20;           // 0x12d78
    function_107bc("miner_type_hash %16llx, bmu_hash %16llx\n", i_v17,
                   (int32_t)(i_v21 / 0x100000000), (int32_t)i_v21);
    uint64_t i_v22 = *(int64_t *)i_v18;  // 0x12d88
    int32_t i_v23 = i_v22;               // 0x12d88
    int32_t i_v24 = i_v22 / 0x100000000; // 0x12d88
    uint64_t i_v25 = *p_v20;             // 0x12d8c
    int32_t i_v26 = i_v25;               // 0x12d8c
    if (i_v26 == i_v23) {
        if ((int32_t)(i_v25 / 0x100000000) == i_v24) {
            char *p_v27 = (char *)(i_v1 - 5); // 0x12dc8
            *p_v27 = 0;
            int32_t i_v28 =
                __asm_sxth(256 * (int32_t) * (char *)(*p_v5 + 11)); // 0x12dd8
            uint32_t i_v29 =
                __asm_sxth(__asm_sxth((int32_t) * (char *)(*p_v5 + 12)) |
                           i_v28);                   // 0x12dec
            int16_t *p_v30 = (int16_t *)(i_v1 - 46); // 0x12df0
            *p_v30 = (int16_t)i_v29;
            if (*(char *)(i_v1 + 12) != 0) {
                uint32_t i_v31 = i_v29 % 0x10000; // 0x12e00
                function_107bc("content:%x\n", i_v31, i_v28, i_v31);
                uint16_t i_v32 = *p_v30; // 0x12e14
                if (i_v32 <= 0xfdff) {
                    // 0x12e24
                    function_107f0("This Package Was Not Full Package!", i_v31,
                                   i_v28, (int32_t)(i_v32 & -512));
                    // 0x13730
                    return 20;
                }
            }
            int32_t *p_v33 = (int32_t *)(i_v1 - 12); // 0x12e3c
            *p_v33 = 0;
            int32_t i_v34 = 0;     // 0x12e6c
            int32_t i_v35 = i_v34; // 0x12e58
            if ((1 << i_v34 & (int32_t)*p_v30) != 0) {
                // 0x12e5c
                *p_v27 = *p_v27 + 1;
                i_v35 = *p_v33;
            }
            // 0x12e68
            i_v34 = i_v35 + 1;
            *p_v33 = i_v34;
            while (i_v34 < 16) {
                // 0x12e44
                i_v35 = i_v34;
                if ((1 << i_v34 & (int32_t)*p_v30) != 0) {
                    // 0x12e5c
                    *p_v27 = *p_v27 + 1;
                    i_v35 = *p_v33;
                }
                // 0x12e68
                i_v34 = i_v35 + 1;
                *p_v33 = i_v34;
            }
            unsigned char i_v36 = *(char *)(*p_v5 + 1304); // 0x12e84
            unsigned char i_v37 = *p_v27;                  // 0x12e88
            int32_t i_v38 = i_v36;
            if (i_v37 != i_v36) {
                int32_t i_v39 = i_v37; // 0x12ea0
                function_107bc("Content Doesn't Match![%d][%d]\n", i_v38, i_v39,
                               i_v39);
                int32_t i_v40 = *p_v10; // 0x12eb4
                if (i_v40 != 0) {
                    // 0x12ec0
                    function_10738(i_v40);
                }
                // 0x13730
                return 9;
            }
            int32_t *p_v41 = (int32_t *)(i_v1 - 16); // 0x12ee0
            *p_v41 = 256 * i_v38 + 2304;
            int32_t i_v42 = *p_v5;                         // 0x12ee4
            unsigned char i_v43 = *(char *)(i_v42 + 1305); // 0x12ee8
            unsigned char i_v44 = *(char *)(i_v42 + 1306); // 0x12ef4
            unsigned char i_v45 = *(char *)(i_v42 + 1307); // 0x12f04
            unsigned char i_v46 = *(char *)(i_v42 + 1308); // 0x12f14
            int32_t *p_v47 = (int32_t *)(i_v1 - 52);       // 0x12f1c
            *p_v47 = 0x10000 * (int32_t)i_v44 | 0x1000000 * (int32_t)i_v43 |
                     256 * (int32_t)i_v45 | (int32_t)i_v46;
            int32_t *p_v48 = (int32_t *)(i_v1 - 20); // 0x12f24
            *p_v48 = 0;
            if (*p_v27 != 0) {
                int32_t *p_v49 = (int32_t *)(i_v1 - 88);       // 0x12fd0
                int32_t i_v50 = *p_v5;                         // 0x12f40
                unsigned char i_v51 = *(char *)(i_v50 + 1310); // 0x12f4c
                unsigned char i_v52 = *(char *)(i_v50 + 1311); // 0x12f74
                unsigned char i_v53 = *(char *)(i_v50 + 1312); // 0x12f9c
                unsigned char i_v54 = *(char *)(i_v50 + 1313); // 0x12fc8
                int32_t i_v55 =
                    0x10000 * (int32_t)i_v52 | 0x1000000 * (int32_t)i_v51 |
                    256 * (int32_t)i_v53 | (int32_t)i_v54; // 0x12fcc
                *p_v49 = i_v55;
                int32_t i_v56 = i_v55 + *p_v41; // 0x12fdc
                *p_v41 = i_v56;
                function_107bc("file[%d] size:[%d]\n", *p_v48, *p_v49, i_v56);
                int32_t i_v57 = *p_v48 + 1; // 0x12ffc
                *p_v48 = i_v57;
                while (i_v57 < (int32_t)*p_v27) {
                    // 0x12f2c
                    i_v50 = *p_v5 + 5 * i_v57;
                    i_v51 = *(char *)(i_v50 + 1310);
                    i_v52 = *(char *)(i_v50 + 1311);
                    i_v53 = *(char *)(i_v50 + 1312);
                    i_v54 = *(char *)(i_v50 + 1313);
                    i_v55 = 0x10000 * (int32_t)i_v52 |
                            0x1000000 * (int32_t)i_v51 | 256 * (int32_t)i_v53 |
                            (int32_t)i_v54;
                    *p_v49 = i_v55;
                    i_v56 = i_v55 + *p_v41;
                    *p_v41 = i_v56;
                    function_107bc("file[%d] size:[%d]\n", *p_v48, *p_v49,
                                   i_v56);
                    i_v57 = *p_v48 + 1;
                    *p_v48 = i_v57;
                }
            }
            int32_t i_v58 = *p_v41; // 0x13014
            int32_t i_v59 = *p_v7;  // 0x13018
            if (i_v58 != i_v59) {
                int32_t i_v60 = *p_v47; // 0x1302c
                function_107bc(
                    "Check FileSize Failed, FileSize Should Be [%d]Bytes, But "
                    "It Was [%d] Bytes, And Total Says[%d]\n",
                    i_v60, i_v59, i_v58);
                int32_t i_v61 = *p_v10; // 0x1303c
                if (i_v61 != 0) {
                    // 0x13048
                    function_10738(i_v61);
                }
                // 0x13730
                return 10;
            }
            int32_t i_v62 =
                function_10798(*p_v4, "r", i_v58, (int32_t *)i_v58); // 0x13064
            int32_t *p_v63 = (int32_t *)(i_v1 - 56);                 // 0x13068
            *p_v63 = i_v62;
            if (i_v62 == 0) {
                // 0x13078
                function_107bc("Cannot Open Root PublicKey '%s'!\n", *p_v4,
                               i_v58, 0);
                int32_t i_v64 = *p_v10; // 0x13088
                if (i_v64 != 0) {
                    // 0x13094
                    function_10738(i_v64);
                }
                // 0x13730
                return 11;
            }
            int32_t i_v65 = i_v1 - 1228;       // 0x130a8
            int32_t *p_v66 = (int32_t *)i_v65; // 0x130a8
            *p_v66 = 0;
            int32_t *p_v67 = (int32_t *)(i_v1 - 1224); // 0x130c4
            function_10744(p_v67, 0, 1020, p_v67);
            function_1082c(p_v66, 1024, 1, *p_v63);
            function_10738(*p_v63);
            *p_v63 = 0;
            int32_t i_v68 = *p_v5;                       // 0x130f4
            unsigned char i_v69 = *(char *)(i_v68 + 23); // 0x13104
            int32_t i_v70 = 256 * (int32_t) * (char *)(i_v68 + 22) |
                            (int32_t)i_v69;          // 0x13108
            int32_t *p_v71 = (int32_t *)(i_v1 - 60); // 0x1310c
            *p_v71 = i_v70;
            int32_t i_v72 = *p_v5;        // 0x13110
            int32_t i_v73 = i_v72 + 1048; // 0x13124
            int32_t i_v74 =
                function_10c70(i_v72 + 24, i_v70, i_v73, i_v65); // 0x13134
            int32_t *p_v75 = (int32_t *)(i_v1 - 64);             // 0x13138
            *p_v75 = i_v74;
            if (i_v74 != 0) {
                // 0x13148
                function_107bc("Check pem payload failed! ret:[%d]\n", i_v74,
                               i_v73, i_v74);
                int32_t i_v76 = *p_v10; // 0x13158
                if (i_v76 != 0) {
                    // 0x13164
                    function_10738(i_v76);
                }
                // 0x13730
                return *p_v75;
            }
            char *p_v77 = (char *)(i_v1 + 4); // 0x13174
            unsigned char i_v78 = *p_v77;     // 0x13174
            if (i_v78 != 0) {
                int32_t i_v79 =
                    function_10798((int32_t) "/tmp/tmpfw/miner.pem", "w", i_v73,
                                   (int32_t *)(int32_t)i_v78); // 0x13190
                int32_t *p_v80 = (int32_t *)(i_v1 - 68);       // 0x13194
                *p_v80 = i_v79;
                if (i_v79 == 0) {
                    // 0x131ec
                    function_107f0("Dump Miner.pem Failed!\r", (int32_t) "w",
                                   i_v73, 0);
                    // 0x13730
                    return 15;
                }
                int32_t i_v81 = *p_v71; // 0x131ac
                function_107d4((int32_t *)(*p_v5 + 24), 1, i_v81, i_v79);
                function_10738(*p_v80);
                int32_t i_v82 =
                    function_10798((int32_t) "/tmp/tmpfw/miner.pem.sig", "w",
                                   i_v81, (int32_t *)i_v79); // 0x131d4
                *p_v80 = i_v82;
                if (i_v82 == 0) {
                    // 0x13228
                    function_107f0("Dump Miner.pem.sig Failed!\r",
                                   (int32_t) "w", i_v81, 0);
                    // 0x13730
                    return 16;
                }
                // 0x13200
                function_107d4((int32_t *)(*p_v5 + 1048), 1, 256, i_v82);
                function_10738(*p_v80);
            }
            int32_t i_v83 = i_v1 - 2284;       // 0x13244
            int32_t *p_v84 = (int32_t *)i_v83; // 0x13254
            function_10744(p_v84, 0, 1056, p_v84);
            int32_t *p_v85 = (int32_t *)(i_v1 - 2396); // 0x13268
            function_10820(p_v85);
            function_10808(p_v85, *p_v5, 2048, p_v85);
            function_10774(p_v84, p_v85, p_v85, p_v84);
            int32_t *p_v86 = (int32_t *)(i_v1 - 24); // 0x132b0
            *p_v86 = 0;
            if (*p_v27 != 0) {
                int32_t i_v87 = i_v1 - 2252;                   // 0x1336c
                int32_t i_v88 = *p_v5;                         // 0x132cc
                unsigned char i_v89 = *(char *)(i_v88 + 1310); // 0x132d8
                unsigned char i_v90 = *(char *)(i_v88 + 1311); // 0x13300
                unsigned char i_v91 = *(char *)(i_v88 + 1312); // 0x13328
                unsigned char i_v92 = *(char *)(i_v88 + 1313); // 0x13354
                int32_t i_v93 =
                    0x10000 * (int32_t)i_v90 | 0x1000000 * (int32_t)i_v89 |
                    256 * (int32_t)i_v91 | (int32_t)i_v92; // 0x13358
                *(int32_t *)(i_v1 - 84) = i_v93;
                int32_t i_v94 = *p_v86; // 0x13364
                unsigned char i_v95 =
                    *(char *)(5 * i_v94 + 1309 + *p_v5); // 0x133a0
                function_10de8(*p_v10, i_v93, i_v87 + 32 * i_v94,
                               (int32_t)i_v95, 0, (int32_t)*p_v77);
                int32_t i_v96 = *p_v86 + 1; // 0x133cc
                *p_v86 = i_v96;
                while (i_v96 < (int32_t)*p_v27) {
                    // 0x132b8
                    i_v88 = *p_v5 + 5 * i_v96;
                    i_v89 = *(char *)(i_v88 + 1310);
                    i_v90 = *(char *)(i_v88 + 1311);
                    i_v91 = *(char *)(i_v88 + 1312);
                    i_v92 = *(char *)(i_v88 + 1313);
                    i_v93 = 0x10000 * (int32_t)i_v90 |
                            0x1000000 * (int32_t)i_v89 | 256 * (int32_t)i_v91 |
                            (int32_t)i_v92;
                    *(int32_t *)(i_v1 - 84) = i_v93;
                    i_v94 = *p_v86;
                    i_v95 = *(char *)(5 * i_v94 + 1309 + *p_v5);
                    function_10de8(*p_v10, i_v93, i_v87 + 32 * i_v94,
                                   (int32_t)i_v95, 0, (int32_t)*p_v77);
                    i_v96 = *p_v86 + 1;
                    *p_v86 = i_v96;
                }
            }
            int32_t *p_v97 = (int32_t *)(i_v1 - 28); // 0x133e8
            *p_v97 = 0;
            unsigned char i_v98 = *p_v27; // 0x13468
            if (i_v98 != 0) {
                int32_t i_v99 = 0; // 0x13460
                unsigned char i_v100 =
                    *(char *)(5 * i_v99 + 1309 + *p_v5); // 0x13434
                unsigned char i_v101 = *p_v77;           // 0x13438
                int32_t i_v102 = *p_v10;                 // 0x13454
                function_10de8(i_v102, 256,
                               32 * ((int32_t)i_v98 + 1 + i_v99) + i_v83,
                               (int32_t)i_v100, 1, (int32_t)i_v101);
                i_v99 = *p_v97 + 1;
                *p_v97 = i_v99;
                int32_t i_v103 = (int32_t)*p_v27; // 0x13468
                while (i_v99 < i_v103) {
                    // 0x133f0
                    i_v100 = *(char *)(5 * i_v99 + 1309 + *p_v5);
                    i_v101 = *p_v77;
                    i_v102 = *p_v10;
                    function_10de8(i_v102, 256,
                                   32 * (i_v103 + 1 + i_v99) + i_v83,
                                   (int32_t)i_v100, 1, (int32_t)i_v101);
                    i_v99 = *p_v97 + 1;
                    *p_v97 = i_v99;
                    i_v103 = (int32_t)*p_v27;
                }
            }
            int32_t i_v104 = i_v1 - 2652;        // 0x1347c
            int32_t *p_v105 = (int32_t *)i_v104; // 0x1347c
            *p_v105 = 0;
            int32_t *p_v106 = (int32_t *)(i_v1 - 2648); // 0x13498
            function_10744(p_v106, 0, 252, p_v106);
            function_1075c(*p_v10, -256, 2);
            function_1082c(p_v105, 256, 1, *p_v10);
            int32_t i_v107 = i_v1 - 2684;        // 0x134cc
            int32_t *p_v108 = (int32_t *)i_v107; // 0x134cc
            *p_v108 = 0;
            *(int32_t *)(i_v1 - 2680) = 0;
            *(int32_t *)(i_v1 - 2676) = 0;
            *(int32_t *)(i_v1 - 2672) = 0;
            *(int32_t *)(i_v1 - 2668) = 0;
            *(int32_t *)(i_v1 - 2664) = 0;
            *(int32_t *)(i_v1 - 2660) = 0;
            *(int32_t *)(i_v1 - 2656) = 0;
            int32_t *p_v109 = (int32_t *)(i_v1 - 2796); // 0x1350c
            function_10820(p_v109);
            function_10808(p_v109, i_v83, 64 * (int32_t)*p_v27 | 32, p_v109);
            function_10774(p_v108, p_v109, p_v109, p_v108);
            int32_t *p_v110 = (int32_t *)(i_v1 - 72); // 0x13568
            *p_v110 = 0;
            int32_t *p_v111 = (int32_t *)(i_v1 - 76); // 0x13570
            *p_v111 = 0;
            int32_t i_v112 = function_107a4(*p_v5 + 24, 1024); // 0x13584
            *p_v110 = i_v112;
            int32_t i_v113 = function_10768(i_v112, 0, 0, 0); // 0x1359c
            *p_v111 = i_v113;
            if (i_v113 == 0) {
                int32_t i_v114 =
                    function_107c8(function_10714(0), 0); // 0x135c0
                function_107bc("OpenSSL error: %s\n", i_v114, 0, i_v114);
                function_107f0("Load Pem Failed!", i_v114, 0, i_v114);
                // 0x13730
                return 17;
            }
            int32_t i_v115 =
                function_10750(672, p_v108, 32, i_v104, 256, i_v113); // 0x1361c
            int32_t *p_v116 = (int32_t *)(i_v1 - 80);                 // 0x13620
            *p_v116 = i_v115;
            int32_t i_v117 = *p_v111; // 0x13624
            if (i_v117 != 0) {
                // 0x13630
                function_107fc(i_v117);
            }
            int32_t i_v118 = *p_v110; // 0x13638
            if (i_v118 != 0) {
                // 0x13644
                function_10814(i_v118);
            }
            int32_t i_v119 = *p_v116; // 0x1364c
            if (i_v119 != 1) {
                int32_t i_v120 = function_107f0("Check File Sig failed!\r",
                                                i_v107, 32, i_v119); // 0x13660
                int32_t i_v121 =
                    function_107c8(function_10714(i_v120), 0); // 0x13674
                function_107bc("OpenSSL error: %s\n", i_v121, 32, i_v121);
                // 0x13730
                return 18;
            }
            int32_t i_v122 = *p_v10; // 0x13694
            if (i_v122 != 0) {
                // 0x136a0
                function_10738(i_v122);
            }
            // 0x136a8
            *p_v10 = 0;
            function_107f0("All Done!\r", i_v107, 32, 0);
            unsigned char i_v123 = *(char *)(i_v1 + 8); // 0x136bc
            if (i_v123 != 0) {
                // 0x136c8
                function_107f0("This Comment Of This Package:", i_v107, 32,
                               (int32_t)i_v123);
                int32_t i_v124 = i_v1 - 3056;        // 0x136d8
                int32_t *p_v125 = (int32_t *)i_v124; // 0x136d8
                *p_v125 = 0;
                int32_t *p_v126 = (int32_t *)(i_v1 - 3052); // 0x136f4
                function_10744(p_v126, 0, 253, p_v126);
                int32_t i_v127 = *p_v5 + 1360; // 0x136fc
                function_1078c(p_v125, i_v127, 256, p_v125);
                function_107f0((char *)i_v124, i_v127, 256, i_v124);
            }
            // 0x13730
            return 0;
        }
    }
    // 0x12d9c
    function_107f0("input miner_type and bmu miner type donot match!", i_v26,
                   i_v24, i_v23);
    int32_t i_v128 = *p_v10; // 0x12da8
    if (i_v128 != 0) {
        // 0x12db4
        function_10738(i_v128);
    }
    // 0x13730
    return 30;
}

// Address range: 0x1373c - 0x13b20
int32_t function_1373c(uint32_t i_a1, int32_t i_a2) {
    // 0x1373c
    if (i_a1 <= 1) {
        // 0x13b14
        return 1;
    }
    int32_t *p_v1 = (int32_t *)(i_a2 + 4); // 0x13780
    if (*(char *)*p_v1 != 45) {
        // 0x13b14
        return 2;
    }
    int32_t i_v2 = 0; // bp-272, 0x137ac
    int32_t i_v3;     // bp-268, 0x1373c
    function_10744(&i_v3, 0, 252, &i_v3);
    int32_t i_v4 = 0; // bp-400, 0x137c8
    int32_t i_v5;     // bp-396, 0x1373c
    function_10744(&i_v5, 0, 124, &i_v5);
    int32_t i_v6 = 0; // bp-528, 0x137e4
    int32_t i_v7;     // bp-524, 0x1373c
    function_10744(&i_v7, 0, 124, &i_v7);
    int32_t i_v8; // bp-2576, 0x1373c
    function_10744(&i_v8, 0, 2048, &i_v8);
    int32_t i_v9; // bp-2832, 0x1373c
    function_10744(&i_v9, 0, 253, &i_v9);
    int32_t i_v10 = 0;   // 0x1373c
    int32_t i_v11 = 253; // 0x1373c
    switch (i_a1) {
    case 5: {
        int32_t *p_v12 = (int32_t *)(i_a2 + 8);             // 0x13868
        uint32_t i_v13 = function_10780((int32_t *)*p_v12); // 0x13870
        if (i_v13 != 255 && i_v13 >= 255) {
            // 0x13880
            function_107f0("fileName Too Long!", 0, 253, i_v13);
            // 0x13b14
            return 3;
        }
        int32_t i_v14 = *p_v12; // 0x1389c
        function_107b0(&i_v2, i_v14);
        int32_t *p_v15 = (int32_t *)(i_a2 + 12);            // 0x138b8
        uint32_t i_v16 = function_10780((int32_t *)*p_v15); // 0x138c0
        if (i_v16 != 127 && i_v16 >= 127) {
            // 0x138d0
            function_107f0("fileName Too Long!", i_v14, i_v14, i_v16);
            // 0x13b14
            return 3;
        }
        int32_t i_v17 = *p_v15; // 0x138ec
        function_107b0(&i_v4, i_v17);
        int32_t *p_v18 = (int32_t *)(i_a2 + 16);            // 0x13908
        uint32_t i_v19 = function_10780((int32_t *)*p_v18); // 0x13910
        if (i_v19 != 127 && i_v19 >= 127) {
            // 0x13920
            function_107f0("pemName Too Long!", i_v17, i_v17, i_v19);
            // 0x13b14
            return 4;
        }
        int32_t i_v20 = *p_v18; // 0x1393c
        function_107b0(&i_v6, i_v20);
        i_v10 = i_v20;
        i_v11 = i_v20;
    }
    case 2: {
    lab_0x139e4:;
        unsigned char i_v21 = *(char *)(*p_v1 + 1); // 0x139fc
        int32_t i_v22 = (int32_t)i_v21 - 102;       // 0x13a00
        i_g6 = i_v22;
        int32_t i_v23; // 0x1373c
        switch (i_v21) {
        case 102: {
        }
        case 120: {
        }
        case 115: {
        }
        case 112: {
            // 0x13a8c
            i_v23 = &i_v4;
            // break -> 0x13b14
            break;
        }
        case 113: {
            // 0x13ae0
            i_v23 = function_10b9c();
            // break -> 0x13b14
            break;
        }
        case 110: {
            // 0x13acc
            i_v23 = function_109a8(&i_v4);
            // break -> 0x13b14
            break;
        }
        default: {
            // 0x13aec
            function_107f0("Command Not Support!", i_v10, i_v11, i_v22);
            i_v23 = 5;
            // break -> 0x13b14
            break;
        }
        }
        // 0x13b14
        return i_v23;
    }
    case 3: {
        int32_t *p_v24 = (int32_t *)(i_a2 + 8);             // 0x13968
        uint32_t i_v25 = function_10780((int32_t *)*p_v24); // 0x13970
        if (i_v25 != 127 && i_v25 >= 127) {
            // 0x13980
            function_107f0("fileName Too Long!", 0, 253, i_v25);
            // 0x13b14
            return 3;
        }
        int32_t i_v26 = *p_v24; // 0x1399c
        function_107b0(&i_v4, i_v26);
        i_v10 = i_v26;
        i_v11 = i_v26;
        // branch (via goto) -> 0x139e4
        goto lab_0x139e4;
    }
    default: {
        // 0x139c0
        function_107f0("Param Err!", 0, 253, i_a1);
        // 0x13b14
        return 3;
    }
    }
}

// Address range: 0x13b20 - 0x13b54
int32_t function_13b20(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_106e8(i_a1, i_a2, i_a3, i_a4); // 0x13b30
    return 0x24f0a - (int32_t)&i_g1 >> 2 == 0 ? i_v1 : i_a1;
}

// Address range: 0x13b5c - 0x13b5e
int32_t function_13b5c(void) {
    // 0x13b5c
    int32_t i_v1; // 0x13b5c
    return i_v1;
}

// Address range: 0x13b60 - 0x13b64
int32_t function_13b60(int32_t i_a1, int32_t i_a2) {
    // 0x13b60
    bool i_v1; // 0x13b60
    if (i_v1) {
        // branch ->
    }
    return i_a1;
}

// Address range: 0x13b64 - 0x13b6a
int32_t function_13b64(void) {
    // 0x13b64
    return function_107e0();
}

// Address range: 0x13b6c - 0x13b74
int32_t function_13b6c(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x13b6c
    return i_a1;
}

// Address range: 0xe0832002 - 0xe0832003
int32_t function_e0832002(void) {
    // 0xe0832002
    int32_t i_v1; // 0xe0832002
    return i_v1;
}

// Address range: 0xe1a00003 - 0xe1a00004
int32_t function_e1a00003(void) {
    // 0xe1a00003
    int32_t i_v1; // 0xe1a00003
    return i_v1;
}

// Address range: 0xe1a02003 - 0xe1a02004
int32_t function_e1a02003(void) {
    // 0xe1a02003
    int32_t i_v1; // 0xe1a02003
    return i_v1;
}

// Address range: 0xe1a03000 - 0xe1a03001
int32_t function_e1a03000(void) {
    // 0xe1a03000
    int32_t i_v1; // 0xe1a03000
    return i_v1;
}

// Address range: 0xe1a0c002 - 0xe1a0c003
int32_t function_e1a0c002(void) {
    // 0xe1a0c002
    int32_t i_v1; // 0xe1a0c002
    return i_v1;
}

// Address range: 0xe1a0e003 - 0xe1a0e004
int32_t function_e1a0e003(void) {
    // 0xe1a0e003
    int32_t i_v1; // 0xe1a0e003
    return i_v1;
}

// Address range: 0xe2433004 - 0xe2433005
int32_t function_e2433004(void) {
    // 0xe2433004
    int32_t i_v1; // 0xe2433004
    return i_v1;
}

// Address range: 0xe243300c - 0xe243300d
int32_t function_e243300c(void) {
    // 0xe243300c
    int32_t i_v1; // 0xe243300c
    return i_v1;
}

// Address range: 0xe24b3e51 - 0xe24b3e52
int32_t function_e24b3e51(void) {
    // 0xe24b3e51
    int32_t i_v1; // 0xe24b3e51
    return i_v1;
}

// Address range: 0xe3033f1c - 0xe3033f1d
int32_t function_e3033f1c(void) {
    // 0xe3033f1c
    int32_t i_v1; // 0xe3033f1c
    return i_v1;
}

// Address range: 0xe3403001 - 0xe3403002
int32_t function_e3403001(void) {
    // 0xe3403001
    int32_t i_v1; // 0xe3403001
    return i_v1;
}

// Address range: 0xe58c0000 - 0xe58c0001
int32_t function_e58c0000(void) {
    // 0xe58c0000
    int32_t i_v1; // 0xe58c0000
    return i_v1;
}

// Address range: 0xe58c1004 - 0xe58c1005
int32_t function_e58c1004(void) {
    // 0xe58c1004
    int32_t i_v1; // 0xe58c1004
    return i_v1;
}

// Address range: 0xe58c2008 - 0xe58c2009
int32_t function_e58c2008(void) {
    // 0xe58c2008
    int32_t i_v1; // 0xe58c2008
    return i_v1;
}

// Address range: 0xe58c300c - 0xe58c300d
int32_t function_e58c300c(void) {
    // 0xe58c300c
    int32_t i_v1; // 0xe58c300c
    return i_v1;
}

// Address range: 0xe8be000f - 0xe8be0010
int32_t function_e8be000f(void) {
    // 0xe8be000f
    int32_t i_v1; // 0xe8be000f
    return i_v1;
}

// Address range: 0xea00004f - 0xea000050
int32_t function_ea00004f(void) {
    // 0xea00004f
    int32_t i_v1; // 0xea00004f
    return i_v1;
}

// Address range: 0xebfffdd2 - 0xebfffdd3
int32_t function_ebfffdd2(void) {
    // 0xebfffdd2
    int32_t i_v1; // 0xebfffdd2
    return i_v1;
}

// Address range: 0xff86c4c8 - 0xff86c4c9
int32_t function_ff86c4c8(void) {
    // 0xff86c4c8
    int32_t i_v1; // 0xff86c4c8
    return i_v1;
}

// Address range: 0xff86c848 - 0xff86c849
int32_t function_ff86c848(void) {
    // 0xff86c848
    int32_t i_v1; // 0xff86c848
    return i_v1;
}

// Address range: 0xff86ce70 - 0xff86ce71
int32_t function_ff86ce70(void) {
    // 0xff86ce70
    int32_t i_v1; // 0xff86ce70
    return i_v1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.3)
// Detected functions: 79
