//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t __libc_start_main(void);
int32_t abort(void);
int32_t access(void);
int32_t close(void);
int32_t entry_point(int32_t i_a1, int32_t i_a2);
int32_t execvp(void);
int32_t exit(void);
int32_t fclose(void);
int32_t fopen(void);
int32_t fork(void);
int32_t fscanf(void);
int32_t function_8550(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_8600(void);
int32_t function_8654(int32_t i_a1, int32_t i_a2);
int32_t function_8850(void);
int32_t function_8874(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4);
int32_t function_88ac(int32_t * p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_88ec(void);
int32_t function_8914(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_8948(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_8968(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_8988(char * p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_89a0(void);
int32_t function_8a84(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_8ae8(void);
int32_t function_8aec(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t fwrite(void);
int32_t gettimeofday(void);
int32_t printf(void);
int32_t puts(void);
int32_t sleep(void);
int32_t system(void);
int32_t usleep(void);
int32_t wait(void);

// --------------------- Global Variables ---------------------

int32_t i_g1 = 0; // 0x10d44
int32_t i_g2 = 0; // 0x10e88
char * p_g3; // 0x10e94
int32_t i_g4 = 0; // 0x8290
int32_t i_g5 = 0x8570; // 0x829c
int32_t i_g6 = -0x1e4f9eba; // 0x8aac

// ------------------------ Functions -------------------------

// Address range: 0x8550 - 0x855c
int32_t function_8550(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x8550
    return function_8850();
}

// Address range: 0x8570 - 0x857c
int32_t printf(void) {
    // 0x8570
    int32_t i_v1; // 0x8570
    return i_v1;
}

// Address range: 0x857c - 0x8588
int32_t fscanf(void) {
    // 0x857c
    int32_t i_v1; // 0x857c
    return i_v1;
}

// Address range: 0x8588 - 0x8594
int32_t fopen(void) {
    // 0x8588
    int32_t i_v1; // 0x8588
    return i_v1;
}

// Address range: 0x8594 - 0x85a0
int32_t execvp(void) {
    // 0x8594
    int32_t i_v1; // 0x8594
    return i_v1;
}

// Address range: 0x85a0 - 0x85ac
int32_t sleep(void) {
    // 0x85a0
    int32_t i_v1; // 0x85a0
    return i_v1;
}

// Address range: 0x85ac - 0x85b8
int32_t wait(void) {
    // 0x85ac
    int32_t i_v1; // 0x85ac
    return i_v1;
}

// Address range: 0x85b8 - 0x85c4
int32_t fwrite(void) {
    // 0x85b8
    int32_t i_v1; // 0x85b8
    return i_v1;
}

// Address range: 0x85c4 - 0x85d0
int32_t usleep(void) {
    // 0x85c4
    int32_t i_v1; // 0x85c4
    return i_v1;
}

// Address range: 0x85d0 - 0x85dc
int32_t gettimeofday(void) {
    // 0x85d0
    int32_t i_v1; // 0x85d0
    return i_v1;
}

// Address range: 0x85dc - 0x85e8
int32_t puts(void) {
    // 0x85dc
    int32_t i_v1; // 0x85dc
    return i_v1;
}

// Address range: 0x85e8 - 0x85f4
int32_t __libc_start_main(void) {
    // 0x85e8
    int32_t i_v1; // 0x85e8
    return i_v1;
}

// Address range: 0x85f4 - 0x8600
int32_t system(void) {
    // 0x85f4
    int32_t i_v1; // 0x85f4
    return i_v1;
}

// Address range: 0x8600 - 0x860c
int32_t function_8600(void) {
    // 0x8600
    int32_t i_v1; // 0x8600
    return i_v1;
}

// Address range: 0x860c - 0x8618
int32_t exit(void) {
    // 0x860c
    int32_t i_v1; // 0x860c
    return i_v1;
}

// Address range: 0x8618 - 0x8624
int32_t access(void) {
    // 0x8618
    int32_t i_v1; // 0x8618
    return i_v1;
}

// Address range: 0x8624 - 0x8630
int32_t fclose(void) {
    // 0x8624
    int32_t i_v1; // 0x8624
    return i_v1;
}

// Address range: 0x8630 - 0x863c
int32_t fork(void) {
    // 0x8630
    int32_t i_v1; // 0x8630
    return i_v1;
}

// Address range: 0x863c - 0x8648
int32_t abort(void) {
    // 0x863c
    int32_t i_v1; // 0x863c
    return i_v1;
}

// Address range: 0x8648 - 0x8654
int32_t close(void) {
    // 0x8648
    int32_t i_v1; // 0x8648
    return i_v1;
}

// Address range: 0x8654 - 0x87f0
int32_t function_8654(int32_t i_a1, int32_t i_a2) {
    // 0x8654
    printf();
    int32_t i_v1 = 0;
    int32_t i_v2 = (int32_t)"11:08:51"; // 0x8670
    int32_t i_v3; // 0x8654
    int32_t i_v4; // 0x8654
    int32_t i_v5; // 0x8654
    while (true) {
        int32_t i_v6 = i_v2; // 0x8680
        int32_t i_v7; // 0x8654
        int32_t i_v8 = i_v7; // 0x8680
        int32_t i_v9 = i_v7; // 0x8680
        if (function_89a0() == 0) {
            while (true) {
                // 0x8684
                function_8948(gettimeofday(), 0, i_v6, i_v8);
                puts();
                i_v3 = i_v6;
                i_v4 = i_v8;
                if (function_89a0() != 1) {
                    while (true) {
                      lab_generated_0:
                        gettimeofday();
                        while (i_v1 >= 0x2dc6c1) {
                            // 0x86e8
                            puts();
                            if (function_89a0() == 0) {
                                function_8948(0, i_v5, i_v1, 0x2dc6c0);
                                function_8968(sleep(), i_v5, i_v1, 0x2dc6c0);
                                sleep();
                                while (function_89a0() == 0) {
                                    // 0x86f4
                                    function_8948(0, i_v5, i_v1, 0x2dc6c0);
                                    function_8968(sleep(), i_v5, i_v1, 0x2dc6c0);
                                    sleep();
                                }
                            }
                            // 0x871c
                            puts();
                            int32_t i_v10 = fork(); // 0x8724
                            if (i_v10 < 0) {
                                // 0x87b8
                                puts();
                                goto lab_0x86a0;
                            }
                            if (i_v10 == 0) {
                                // break (via goto) -> 0x87c4
                                goto lab_0x87c4;
                            }
                            // 0x8734
                            wait();
                            int32_t i_v11 = puts(); // 0x8744
                            int32_t i_v12 = 100;
                            function_8948(i_v11, i_v5, i_v1, 0x2dc6c0);
                            function_8968(usleep(), i_v5, i_v1, 0x2dc6c0);
                            i_v11 = usleep();
                            int32_t i_v13 = i_v12 - 1; // 0x876c
                            while (i_v12 != 1) {
                                // 0x8748
                                i_v12 = i_v13;
                                function_8948(i_v11, i_v5, i_v1, 0x2dc6c0);
                                function_8968(usleep(), i_v5, i_v1, 0x2dc6c0);
                                i_v11 = usleep();
                                i_v13 = i_v12 - 1;
                            }
                            // 0x8770
                            puts();
                            i_v3 = i_v1;
                            i_v4 = 0x2dc6c0;
                            if (function_89a0() == 1) {
                                // break (via goto) -> 0x8788
                                goto lab_0x8788_2;
                            }
                            gettimeofday();
                        }
                        // 0x87a8
                        usleep();
                        goto lab_0x86a0;
                    }
                }
              lab_0x8788_2:
                // 0x8788
                function_8968(1, 0, i_v3, i_v4);
                i_v6 = i_v3;
                i_v8 = i_v4;
                i_v2 = i_v3;
                i_v9 = i_v4;
                if (function_89a0() != 0) {
                    // break -> 0x879c
                    break;
                }
            }
        }
        // 0x879c
        sleep();
        i_v7 = i_v9;
    }
  lab_0x87c4:
    // 0x87c4
    function_8968(0, i_v5, i_v1, 0x2dc6c0);
    if (i_a1 < 2) {
        // 0x87e4
        sleep();
        // 0x87dc
        exit();
        // 0x87e4
        sleep();
        goto lab_0x87dc;
    } else {
        // 0x87d0
        execvp();
        // 0x87dc
        exit();
        // 0x87e4
        sleep();
        goto lab_0x87dc;
    }
  lab_0x86a0:
    // 0x86a0
    i_v3 = i_v1;
    i_v4 = 0x2dc6c0;
    if (function_89a0() == 1) {
        // break -> 0x8788
        goto lab_0x8788_2;
    }
    goto lab_generated_1;
}

// Address range: 0x8814 - 0x8844
int32_t entry_point(int32_t i_a1, int32_t i_a2) {
    // 0x8814
    __libc_start_main();
    return abort();
}

// Address range: 0x8850 - 0x886c
int32_t function_8850(void) {
    // 0x8850
    if (i_g2 == 0) {
        int32_t i_v1; // 0x8850
        return i_v1;
    }
    // 0x8868
    return function_8600();
}

// Address range: 0x8874 - 0x88a0
int32_t function_8874(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4) {
    // 0x8874
    return (int32_t)&p_g3;
}

// Address range: 0x88ac - 0x88e0
int32_t function_88ac(int32_t * p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x88ac
    return (int32_t)&p_g3;
}

// Address range: 0x88ec - 0x8910
int32_t function_88ec(void) {
    // 0x88ec
    int32_t i_v1; // 0x88ec
    if (*(char *)&p_g3 != 0) {
        return i_v1;
    }
    int32_t i_v2 = function_8874(i_v1, i_v1, i_v1, 0); // 0x8900
    *(char *)&p_g3 = 1;
    return i_v2;
}

// Address range: 0x8914 - 0x8940
int32_t function_8914(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x8914
    return function_88ac(&i_g1, i_a2, i_a3, i_a4);
}

// Address range: 0x8948 - 0x8968
int32_t function_8948(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x8948
    system();
    return system();
}

// Address range: 0x8968 - 0x8988
int32_t function_8968(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x8968
    system();
    return system();
}

// Address range: 0x8988 - 0x89a0
int32_t function_8988(char * p_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    uint32_t i_v1 = access(); // 0x8990
    return (i_v1 > 1 ? i_v1 : 1) - i_v1;
}

// Address range: 0x89a0 - 0x8a5c
int32_t function_89a0(void) {
    // 0x89a0
    int32_t i_v1; // 0x89a0
    int32_t i_v2 = function_8988("/sys/class/gpio/gpio921", i_v1, i_v1, i_v1); // 0x89ac
    int32_t i_v3 = fopen();
    if (i_v2 != 0) {
        int32_t i_v4; // 0x89a0
        if (i_v3 == 0) {
            // 0x8a3c
            puts();
            i_v4 = -1;
        } else {
            // 0x8a18
            fscanf();
            close();
            i_v4 = i_v1 != 0;
        }
        // 0x89fc
        return i_v4;
    }
    if (i_v3 == 0) {
        // 0x8a4c
        puts();
        // 0x89fc
        return -1;
    }
    // 0x89cc
    if (fwrite() != 1) {
        // 0x89e8
        puts();
    }
    // 0x89f0
    fclose();
    // 0x89fc
    return -1;
}

// Address range: 0x8a84 - 0x8ae0
int32_t function_8a84(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_8550(i_a1, i_a2, i_a3, i_a4); // 0x8aa0
    int32_t i_v2 = (int32_t)&i_g5 + 0x8aa4 - ((int32_t)&i_g6 + (int32_t)&i_g4) >> 2 == 0 ? i_v1 : i_a1;
    return i_v2;
}

// Address range: 0x8ae8 - 0x8aec
int32_t function_8ae8(void) {
    // 0x8ae8
    int32_t i_v1; // 0x8ae8
    return i_v1;
}

// Address range: 0x8aec - 0x8af4
int32_t function_8aec(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x8aec
    return i_a1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.8.x)
// Detected functions: 34

