//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t entry_point(int32_t i_a1, int32_t i_a2);
int32_t function_103a0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_103c0(void);
int32_t function_103cc(void);
int32_t function_103d8(void);
int32_t function_103e4(void);
int32_t function_103f0(void);
int32_t function_103fc(void);
int32_t function_10408(void);
int32_t function_10414(void);
int32_t function_10420(void);
int32_t function_1042c(void);
int32_t function_10438(void);
int32_t function_10498(void);
int32_t function_104bc(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4);
int32_t function_104e6(int32_t i_a1, int32_t i_a2);
int32_t function_1050c(void);
int32_t function_10524(int32_t i_a1, int32_t i_a2);
int32_t function_1057c(int32_t i_a1, int32_t i_a2);
int32_t function_105b0(int32_t *p_a1, int32_t *p_a2);
int32_t function_106c8(int32_t *p_a1);
int32_t function_108b0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_108ec(void);
int32_t function_108f0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4);
int32_t function_24104c8(void);

// --------------------- Global Variables ---------------------

// Detected cryptographic pattern: CRC_32_IEEE_802_3_poly_0x04C11DB7 (32-bit,
// little endian)
int32_t CRC_32_IEEE_802_3_poly_0x04C11DB7_at_108fc[256] = {
    0,           0x4c11db7,   0x9823b6e,   0xd4326d9,   0x130476dc,
    0x17c56b6b,  0x1a864db2,  0x1e475005,  0x2608edb8,  0x22c9f00f,
    0x2f8ad6d6,  0x2b4bcb61,  0x350c9b64,  0x31cd86d3,  0x3c8ea00a,
    0x384fbdbd,  0x4c11db70,  0x48d0c6c7,  0x4593e01e,  0x4152fda9,
    0x5f15adac,  0x5bd4b01b,  0x569796c2,  0x52568b75,  0x6a1936c8,
    0x6ed82b7f,  0x639b0da6,  0x675a1011,  0x791d4014,  0x7ddc5da3,
    0x709f7b7a,  0x745e66cd,  -0x67dc4920, -0x631d54a9, -0x6e5e7272,
    -0x6a9f6fc7, -0x74d83fc4, -0x70192275, -0x7d5a04ae, -0x799b191b,
    -0x41d4a4a8, -0x4515b911, -0x48569fca, -0x4c97827f, -0x52d0d27c,
    -0x5611cfcd, -0x5b52e916, -0x5f93f4a3, -0x2bcd9270, -0x2f0c8fd9,
    -0x224fa902, -0x268eb4b7, -0x38c9e4b4, -0x3c08f905, -0x314bdfde,
    -0x358ac26b, -0xdc57fd8,  -0x9046261,  -0x44744ba,  -0x86590f,
    -0x1ec1090c, -0x1a0014bd, -0x17433266, -0x13822fd3, 0x34867077,
    0x30476dc0,  0x3d044b19,  0x39c556ae,  0x278206ab,  0x23431b1c,
    0x2e003dc5,  0x2ac12072,  0x128e9dcf,  0x164f8078,  0x1b0ca6a1,
    0x1fcdbb16,  0x18aeb13,   0x54bf6a4,   0x808d07d,   0xcc9cdca,
    0x7897ab07,  0x7c56b6b0,  0x71159069,  0x75d48dde,  0x6b93dddb,
    0x6f52c06c,  0x6211e6b5,  0x66d0fb02,  0x5e9f46bf,  0x5a5e5b08,
    0x571d7dd1,  0x53dc6066,  0x4d9b3063,  0x495a2dd4,  0x44190b0d,
    0x40d816ba,  -0x535a3969, -0x579b24e0, -0x5ad80207, -0x5e191fb2,
    -0x405e4fb5, -0x449f5204, -0x49dc74db, -0x4d1d696e, -0x7552d4d1,
    -0x7193c968, -0x7cd0efbf, -0x7811f20a, -0x6656a20d, -0x6297bfbc,
    -0x6fd49963, -0x6b1584d6, -0x1f4be219, -0x1b8affb0, -0x16c9d977,
    -0x1208c4c2, -0xc4f94c5,  -0x88e8974,  -0x5cdafab,  -0x10cb21e,
    -0x39430fa1, -0x3d821218, -0x30c134cf, -0x3400297a, -0x2a47797d,
    -0x2e8664cc, -0x23c54213, -0x27045fa6, 0x690ce0ee,  0x6dcdfd59,
    0x608edb80,  0x644fc637,  0x7a089632,  0x7ec98b85,  0x738aad5c,
    0x774bb0eb,  0x4f040d56,  0x4bc510e1,  0x46863638,  0x42472b8f,
    0x5c007b8a,  0x58c1663d,  0x558240e4,  0x51435d53,  0x251d3b9e,
    0x21dc2629,  0x2c9f00f0,  0x285e1d47,  0x36194d42,  0x32d850f5,
    0x3f9b762c,  0x3b5a6b9b,  0x315d626,   0x7d4cb91,   0xa97ed48,
    0xe56f0ff,   0x1011a0fa,  0x14d0bd4d,  0x19939b94,  0x1d528623,
    -0xed0a9f2,  -0xa11b447,  -0x75292a0,  -0x3938f29,  -0x1dd4df2e,
    -0x1915c29b, -0x1456e444, -0x1097f9f5, -0x28d8444a, -0x2c1959ff,
    -0x215a7f28, -0x259b6291, -0x3bdc3296, -0x3f1d2f23, -0x325e09fc,
    -0x369f144d, -0x42c17282, -0x46006f37, -0x4b4349f0, -0x4f825459,
    -0x51c5045e, -0x550419eb, -0x58473f34, -0x5c862285, -0x64c99f3a,
    -0x6008828f, -0x6d4ba458, -0x698ab9e1, -0x77cde9e6, -0x730cf453,
    -0x7e4fd28c, -0x7a8ecf3d, 0x5d8a9099,  0x594b8d2e,  0x5408abf7,
    0x50c9b640,  0x4e8ee645,  0x4a4ffbf2,  0x470cdd2b,  0x43cdc09c,
    0x7b827d21,  0x7f436096,  0x7200464f,  0x76c15bf8,  0x68860bfd,
    0x6c47164a,  0x61043093,  0x65c52d24,  0x119b4be9,  0x155a565e,
    0x18197087,  0x1cd86d30,  0x29f3d35,   0x65e2082,   0xb1d065b,
    0xfdc1bec,   0x3793a651,  0x3352bbe6,  0x3e119d3f,  0x3ad08088,
    0x2497d08d,  0x2056cd3a,  0x2d15ebe3,  0x29d4f654,  -0x3a56d987,
    -0x3e97c432, -0x33d4e2e9, -0x3715ff60, -0x2952af5b, -0x2d93b2ee,
    -0x20d09435, -0x24118984, -0x1c5e343f, -0x189f298a, -0x15dc0f51,
    -0x111d12e8, -0xf5a42e3,  -0xb9b5f56,  -0x6d8798d,  -0x219643c,
    -0x764702f7, -0x72861f42, -0x7fc53999, -0x7b042430, -0x6543742b,
    -0x6182699e, -0x6cc14f45, -0x680052f4, -0x504fef4f, -0x548ef2fa,
    -0x59cdd421, -0x5d0cc998, -0x434b9993, -0x478a8426, -0x4ac9a2fd,
    -0x4e08bf4c};           // 0x108fc
int32_t i_g1 = -0x1cae0000; // 0x104a8
int32_t i_g2 = 0x3b5a6b9b;  // 0x10b58
int32_t i_g3 = 0x10525;     // 0x20f10
int32_t i_g4 = 0;           // 0x21040
char *p_g5;                 // 0x21440
int32_t i_g6 = 0;           // 0x21448
int64_t i_g7 = 0;           // 0x21450
int32_t i_g8 = 0;           // 0x21454
int64_t i_g9 = 0;           // 0x21458
int32_t i_g10 = 0;          // 0x2145c

// ------------------------ Functions -------------------------

// Address range: 0x103a0 - 0x103ac
int32_t function_103a0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x103a0
    return function_10498();
}

// Address range: 0x103c0 - 0x103cc
int32_t function_103c0(void) {
    // 0x103c0
    int32_t i_v1; // 0x103c0
    return i_v1;
}

// Address range: 0x103cc - 0x103d8
int32_t function_103cc(void) {
    // 0x103cc
    int32_t i_v1; // 0x103cc
    return i_v1;
}

// Address range: 0x103d8 - 0x103e4
int32_t function_103d8(void) {
    // 0x103d8
    int32_t i_v1; // 0x103d8
    return i_v1;
}

// Address range: 0x103e4 - 0x103f0
int32_t function_103e4(void) {
    // 0x103e4
    int32_t i_v1; // 0x103e4
    return i_v1;
}

// Address range: 0x103f0 - 0x103fc
int32_t function_103f0(void) {
    // 0x103f0
    int32_t i_v1; // 0x103f0
    return i_v1;
}

// Address range: 0x103fc - 0x10408
int32_t function_103fc(void) {
    // 0x103fc
    int32_t i_v1; // 0x103fc
    return i_v1;
}

// Address range: 0x10408 - 0x10414
int32_t function_10408(void) {
    // 0x10408
    int32_t i_v1; // 0x10408
    return i_v1;
}

// Address range: 0x10414 - 0x10420
int32_t function_10414(void) {
    // 0x10414
    int32_t i_v1; // 0x10414
    return i_v1;
}

// Address range: 0x10420 - 0x1042c
int32_t function_10420(void) {
    // 0x10420
    int32_t i_v1; // 0x10420
    return i_v1;
}

// Address range: 0x1042c - 0x10438
int32_t function_1042c(void) {
    // 0x1042c
    int32_t i_v1; // 0x1042c
    return i_v1;
}

// Address range: 0x10438 - 0x10468
int32_t function_10438(void) {
    // 0x10438
    int32_t i_v1; // bp-48, 0x10438
    function_106c8(&i_v1);
    int32_t i_v2; // bp-68, 0x10438
    function_105b0(&i_v1, &i_v2);
    function_103d8();
    return 0;
}

// Address range: 0x10468 - 0x10490
int32_t entry_point(int32_t i_a1, int32_t i_a2) {
    // 0x10468
    function_103e4();
    return function_1042c();
}

// Address range: 0x10498 - 0x104b4
int32_t function_10498(void) {
    int32_t i_v1 =
        *(int32_t *)((int32_t)&i_g1 + (int32_t)&i_g2 + 52); // 0x104a4
    if (i_v1 == 0) {
        int32_t i_v2; // 0x10498
        return i_v2;
    }
    // 0x104b0
    return function_103f0();
}

// Address range: 0x104bc - 0x104e4
int32_t function_104bc(int32_t i_a1, int32_t i_a2, int32_t i_a3, char i_a4) {
    // 0x104bc
    bool i_v1; // 0x104bc
    if (i_v1 && !i_v1 && !i_v1) {
        __asm_svclt(0x4770);
    }
    return i_a1;
}

// Address range: 0x104e6 - 0x1050a
int32_t function_104e6(int32_t i_a1, int32_t i_a2) {
    // 0x104e6
    bool i_v1; // 0x104e6
    return 2 * i_a1 | (int32_t)(bool)i_v1 | 0x20000;
}

// Address range: 0x1050c - 0x10524
int32_t function_1050c(void) {
    // 0x1050c
    int32_t i_v1; // 0x1050c
    if (*(char *)&p_g5 == 0) {
        // 0x1051a
        int32_t i_v2;                                       // 0x1050c
        int32_t i_v3 = function_104bc(i_v2, i_v2, i_v2, 0); // 0x1051a
        *(char *)&p_g5 = 1;
        i_v1 = i_v3;
    }
    // 0x10522
    return i_v1;
}

// Address range: 0x10524 - 0x1057c
int32_t function_10524(int32_t i_a1, int32_t i_a2) {
    if (i_a2 < 1) {
        // 0x10568
        return 0;
    }
    int32_t i_v1 = 0;                   // 0x10540
    int32_t i_v2 = i_a1;                // 0x10540
    unsigned char i_v3 = *(char *)i_v2; // 0x10544
    i_v2++;
    uint32_t i_v4 = *(int32_t *)(4 * (i_v1 / 256 ^ (int32_t)i_v3) +
                                 (int32_t)&i_g4); // 0x10558
    i_v1 = i_v4 % 0x10000 ^ 256 * i_v1 & 0xff00;
    while (i_v2 != i_a2 + i_a1) {
        // 0x10544
        i_v3 = *(char *)i_v2;
        i_v2++;
        i_v4 = *(int32_t *)(4 * (i_v1 / 256 ^ (int32_t)i_v3) + (int32_t)&i_g4);
        i_v1 = i_v4 % 0x10000 ^ 256 * i_v1 & 0xff00;
    }
    // 0x10568
    return i_v1;
}

// Address range: 0x1057c - 0x105b0
// Used cryptographic patterns:
//  - CRC_32_IEEE_802_3_poly_0x04C11DB7 (32-bit, little endian)
int32_t function_1057c(int32_t i_a1, int32_t i_a2) {
    if (i_a2 == 0) {
        // 0x105a8
        int32_t i_v1; // 0x1057c
        return i_v1;
    }
    int32_t i_v2 = i_a1;                // 0x1058c
    unsigned char i_v3 = *(char *)i_v2; // 0x10590
    i_v2++;
    int32_t i_v4; // 0x1057c
    int32_t i_v5 = *(
        int32_t
            *)(4 * (i_v4 / 0x1000000 ^ (int32_t)i_v3) +
               (int32_t)&CRC_32_IEEE_802_3_poly_0x04C11DB7_at_108fc); // 0x1059c
    int32_t i_v6 = i_v5 ^ 256 * i_v4;                                 // 0x105a0
    while (i_v2 != i_a2 + i_a1) {
        // 0x10590
        i_v3 = *(char *)i_v2;
        i_v2++;
        i_v5 =
            *(int32_t *)(4 * (i_v6 / 0x1000000 ^ (int32_t)i_v3) +
                         (int32_t)&CRC_32_IEEE_802_3_poly_0x04C11DB7_at_108fc);
        i_v6 = i_v5 ^ 256 * i_v6;
    }
    // 0x105a8
    return i_v6;
}

// Address range: 0x105b0 - 0x106c8
// Used cryptographic patterns:
//  - CRC_32_IEEE_802_3_poly_0x04C11DB7 (32-bit, little endian)
int32_t function_105b0(int32_t *p_a1, int32_t *p_a2) {
    int32_t i_v1 = (int32_t)p_a1;
    int32_t i_v2 = function_103cc(); // 0x105c8
    int32_t i_v3;                    // 0x105b0
    if (i_v2 == 0) {
        int32_t i_v4 = function_103fc(); // 0x105d8
        i_v3 = i_v4;
        if (i_v4 == 0) {
            // 0x10658
            return function_10414();
        }
    } else {
        // 0x1067c
        *p_a1 = *(int32_t *)i_v2;
        *(int32_t *)(i_v1 + 4) = *(int32_t *)(i_v2 + 4);
        *(int32_t *)(i_v1 + 8) = *(int32_t *)(i_v2 + 8);
        *(int32_t *)(i_v1 + 12) = *(int32_t *)(i_v2 + 12);
        int32_t i_v5 = function_103fc(); // 0x106a0
        i_v3 = i_v5;
        if (i_v5 == 0) {
            // 0x10658
            return function_10414();
        }
    }
    int32_t i_v6 = -1;                  // 0x10638
    int32_t i_v7 = i_v1;                // 0x10628
    unsigned char i_v8 = *(char *)i_v7; // 0x10628
    i_v7++;
    int32_t i_v9 = *(
        int32_t
            *)(4 * (i_v6 / 0x1000000 ^ (int32_t)i_v8) +
               (int32_t)&CRC_32_IEEE_802_3_poly_0x04C11DB7_at_108fc); // 0x10634
    i_v6 = i_v9 ^ 256 * i_v6;
    while (i_v7 != i_v3 + i_v1) {
        // 0x10628
        i_v8 = *(char *)i_v7;
        i_v7++;
        i_v9 =
            *(int32_t *)(4 * (i_v6 / 0x1000000 ^ (int32_t)i_v8) +
                         (int32_t)&CRC_32_IEEE_802_3_poly_0x04C11DB7_at_108fc);
        i_v6 = i_v9 ^ 256 * i_v6;
    }
    // 0x10640
    __asm_ubfx(i_v6, 8, 8);
    __asm_ubfx(i_v6, 16, 8);
    // 0x10658
    return function_10414();
}

// Address range: 0x106c8 - 0x108b0
int32_t function_106c8(int32_t *p_a1) {
    // 0x106c8
    uint64_t i_v1; // 0x10744
    uint64_t i_v2; // 0x10748
    uint64_t i_v3; // 0x10748
    if (i_g6 == 0) {
        while (function_10420() != 0) {
            int32_t i_v4 = function_103c0(); // 0x1072c
            function_10408();
            if (i_v4 != 16) {
                // break -> 0x108a4
                break;
            }
            // 0x10744
            i_v1 = i_g7 / 0x100000000;
            i_v2 = i_g9;
            i_v3 = i_v2 / 0x100000000;
            if ((int32_t)(i_v1 || i_g7) != 0) {
                goto lab_0x10754_2;
            }
            if ((int32_t)(i_v3 || i_v2) != 0) {
                goto lab_0x10754_2;
            }
        }
        // 0x108a4
        return -1;
    }
    int32_t i_v5 = i_g7 / 0x100000000; // 0x10764
    int32_t i_v6 = i_g7;               // 0x10764
    int32_t i_v7 = i_g9 / 0x100000000; // 0x10764
    int32_t i_v8 = i_g9;               // 0x10764
    goto lab_0x10768;
lab_0x10754_2:
    // 0x10754
    i_g6 = 1;
    i_v5 = i_v1;
    i_v6 = i_g7;
    i_v7 = i_v3;
    i_v8 = i_v2;
    goto lab_0x10768;
lab_0x10834:;
    // 0x10834
    int32_t i_v29;               // 0x106c8
    int32_t i_v42 = i_v29 + 1;   // 0x10834
    char i_v43 = *(char *)i_v42; // 0x10834
    int32_t i_v30;               // 0x106c8
    int32_t i_v44 = i_v30 + 1;   // 0x10838
    uint32_t i_v25;              // 0x106c8
    int32_t i_v21 = i_v25 + 1;   // 0x10840
    char i_v22 = i_v43;          // 0x10840
    int32_t i_v23 = i_v44;       // 0x10840
    int32_t i_v24 = i_v42;       // 0x10840
    int32_t i_v37 = i_v44;       // 0x10840
    if (i_v43 == 0) {
        // break -> 0x10884
        goto lab_0x10884_2;
    }
    goto lab_0x10844_2;
lab_0x10768:;
    uint32_t i_v9 = i_v8;
    uint32_t i_v10 = i_v7;
    int32_t i_v11 = i_v6;
    uint32_t i_v12 = i_v5;
    uint32_t i_v13 = 0x800000 * i_v12 ^ i_v12;                 // 0x1076c
    uint32_t i_v14 = 0x800000 * i_v10 ^ i_v10;                 // 0x10784
    uint32_t i_v15 = (0x800000 * i_v11 | i_v12 / 512) ^ i_v11; // 0x1078c
    int32_t i_v16 = i_v13 ^ i_v10 ^ (0x8000000 * i_v9 | i_v10 / 32) ^
                    (0x4000 * i_v15 | i_v13 / 0x40000);         // 0x107a4
    uint32_t i_v17 = (0x800000 * i_v9 | i_v10 / 512) ^ i_v9;    // 0x107a8
    int32_t i_v18 = i_v9 / 32 ^ i_v9 ^ i_v15 ^ i_v15 / 0x40000; // 0x107b0
    i_g8 = i_v18;
    i_g7 = i_v16;
    i_g9 = i_v16 ^ i_v14 ^ (0x4000 * i_v17 | i_v14 / 0x40000) ^
           (i_v16 / 32 | 0x8000000 * i_v18);
    i_g10 = i_v17 / 0x40000 ^ i_v17 ^ i_v18 ^ i_v18 / 32;
    int32_t i_v19;                        // bp-32, 0x106c8
    int32_t i_v20 = (int32_t)&i_v19 - 16; // 0x1084c
    i_v21 = 0;
    i_v22 = 120;
    i_v23 = (int32_t)p_a1;
    i_v24 = (int32_t) "xxxxxxxxxxxx4xxxyxxxxxxxxxxxxxxx";
    while (true) {
    lab_0x10844_2:
        // 0x10844
        i_v25 = i_v21;
        char i_v26 = i_v22;    // 0x106c8
        int32_t i_v27 = i_v23; // 0x106c8
        int32_t i_v28 = i_v24; // 0x106c8
        while (true) {
        lab_0x10844:
            // 0x10844
            i_v29 = i_v28;
            i_v30 = i_v27;
            char i_v31 = i_v26;
            switch (i_v31) {
            case 120: {
                goto lab_0x10894;
            }
            case 121: {
                uint32_t i_v32 =
                    (int32_t) * (char *)(i_v20 + i_v25 / 2); // 0x10850
                uint32_t i_v33 = i_v25 % 2 == 0 ? i_v32 : i_v32 / 16;
                *(char *)i_v30 = *(char *)(i_v33 % 4 + (int32_t) "89abcdef");
                goto lab_0x10834;
            }
            default: {
                // 0x10870
                *(char *)i_v30 = i_v31;
                int32_t i_v34 = i_v30 + 1;   // 0x10874
                int32_t i_v35 = i_v29 + 1;   // 0x10878
                char i_v36 = *(char *)i_v35; // 0x10878
                i_v26 = i_v36;
                i_v27 = i_v34;
                i_v28 = i_v35;
                i_v37 = i_v34;
                if (i_v36 == 0) {
                    // break (via goto) -> 0x10884
                    goto lab_0x10884_2;
                }
                goto lab_0x10844;
            }
            }
        }
    lab_0x10894:;
        // 0x10894
        unsigned char i_v38;             // 0x10850
        uint32_t i_v39 = (int32_t)i_v38; // 0x10850
        int32_t i_v40 = i_v25 % 2 == 0 ? i_v39 % 16 : i_v39 / 16;
        char i_v41 = *(char *)(i_v40 | (int32_t) "0123456789abcdef"); // 0x10894
        *(char *)i_v30 = i_v41;
        goto lab_0x10834;
    }
lab_0x10884_2:
    // 0x10884
    *(char *)i_v37 = 0;
    return 0;
}

// Address range: 0x108b0 - 0x108e4
int32_t function_108b0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    int32_t i_v1 = function_103a0(i_a1, i_a2, i_a3, i_a4); // 0x108c0
    return 0x20f12 - (int32_t)&i_g3 >> 2 == 0 ? i_v1 : i_a1;
}

// Address range: 0x108ec - 0x108ee
int32_t function_108ec(void) {
    // 0x108ec
    int32_t i_v1; // 0x108ec
    return i_v1;
}

// Address range: 0x108f0 - 0x108f8
int32_t function_108f0(int32_t i_a1, int32_t i_a2, int32_t i_a3, int32_t i_a4) {
    // 0x108f0
    return i_a1;
}

// Address range: 0x24104c8 - 0x24104c9
int32_t function_24104c8(void) {
    // 0x24104c8
    int32_t i_v1; // 0x24104c8
    return i_v1;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.4.3)
// Detected functions: 25
